import{NextResponse}from"next/server";import{getAdminSession}from"@/app/lib/admin";import pool from"@/app/lib/postgres";export const dynamic="force-dynamic";export const runtime="nodejs";
const union=`SELECT 'MM_V1' research,trade_date,code,result_1d,result_3d,result_5d FROM momentum_memory_observations WHERE validation_mode='FORWARD' AND observation_flag=true
UNION ALL SELECT 'HAP_V1',trade_date,code,result_1d,result_3d,result_5d FROM high_ai_pullback_observations WHERE validation_mode='FORWARD' AND observation_flag=true AND signal_version='HAP_V1'
UNION ALL SELECT 'AIR_V1',trade_date,code,result_1d,result_3d,result_5d FROM ai_reversal_observations WHERE validation_mode='FORWARD' AND observation_flag=true AND signal_version='AIR_V1'
UNION ALL SELECT 'TPR_V1',trade_date,code,result_1d,result_3d,result_5d FROM trend_pullback_reversal_observations WHERE validation_mode='FORWARD' AND observation_flag=true AND signal_version='TPR_V1'`;
export async function GET(){if(!(await getAdminSession()).isAdmin)return NextResponse.json({success:false,error:"Administrator access required"},{status:403});try{const[summary,overlaps,recent]=await Promise.all([
pool.query(`WITH u AS(${union}) SELECT research,COUNT(*)::int candidates,COUNT(result_5d)::int completed_5d,COUNT(DISTINCT code)::int codes,COUNT(DISTINCT trade_date)::int dates,ROUND(AVG(result_5d),4)avg5,ROUND(PERCENTILE_CONT(.5)WITHIN GROUP(ORDER BY result_5d)::numeric,4)median5,ROUND(100.0*COUNT(*)FILTER(WHERE result_5d>0)/NULLIF(COUNT(result_5d),0),2)positive5 FROM u GROUP BY research ORDER BY research`),
pool.query(`WITH u AS(${union}),g AS(SELECT trade_date,code,ARRAY_AGG(DISTINCT research ORDER BY research) researches,COUNT(DISTINCT research)::int research_count FROM u GROUP BY trade_date,code HAVING COUNT(DISTINCT research)>=2) SELECT g.trade_date,g.code,COALESCE(d.name,g.code)name,g.researches,g.research_count FROM g LEFT JOIN LATERAL(SELECT name FROM daily_stock_results d WHERE d.code=g.code AND d.date::date=g.trade_date ORDER BY d.created_at DESC LIMIT 1)d ON true ORDER BY g.trade_date DESC,g.research_count DESC LIMIT 100`),
pool.query(`WITH u AS(${union}) SELECT u.trade_date,u.code,COALESCE(d.name,u.code)name,u.research,u.result_1d,u.result_3d,u.result_5d FROM u LEFT JOIN LATERAL(SELECT name FROM daily_stock_results d WHERE d.code=u.code AND d.date::date=u.trade_date ORDER BY d.created_at DESC LIMIT 1)d ON true ORDER BY u.trade_date DESC,u.code,u.research LIMIT 100`)
]);return NextResponse.json({success:true,summary:summary.rows,overlaps:overlaps.rows,recent:recent.rows},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error("Research lab API error:",e);return NextResponse.json({success:false,error:"Research Lab data is unavailable"},{status:500})}}