import{NextResponse}from"next/server";import{getAdminSession}from"@/app/lib/admin";import pool from"@/app/lib/postgres";export const dynamic="force-dynamic";export const runtime="nodejs";
const union=`SELECT 'MM_V1' research,trade_date,code,result_1d,result_3d,result_5d FROM momentum_memory_observations WHERE validation_mode='FORWARD' AND observation_flag=true
UNION ALL SELECT 'HAP_V1',trade_date,code,result_1d,result_3d,result_5d FROM high_ai_pullback_observations WHERE validation_mode='FORWARD' AND observation_flag=true AND signal_version='HAP_V1'
UNION ALL SELECT 'AIR_V1',trade_date,code,result_1d,result_3d,result_5d FROM ai_reversal_observations WHERE validation_mode='FORWARD' AND observation_flag=true AND signal_version='AIR_V1'
UNION ALL SELECT 'TPR_V1',trade_date,code,result_1d,result_3d,result_5d FROM trend_pullback_reversal_observations WHERE validation_mode='FORWARD' AND observation_flag=true AND signal_version='TPR_V1'`;
export async function GET(){if(!(await getAdminSession()).isAdmin)return NextResponse.json({success:false,error:"Administrator access required"},{status:403});try{const[summary,overlaps,recent]=await Promise.all([
pool.query(`WITH u0 AS(${union}),u AS(SELECT u0.*,COALESCE(CASE WHEN research='MM_V1' THEN (SELECT ml.market_pattern FROM market_learning_logs ml WHERE ml.trade_date=u0.trade_date ORDER BY ml.created_at DESC LIMIT 1) WHEN research='HAP_V1' THEN (SELECT h.market_pattern FROM high_ai_pullback_observations h WHERE h.trade_date=u0.trade_date AND h.code=u0.code LIMIT 1) WHEN research='AIR_V1' THEN (SELECT a.market_pattern FROM ai_reversal_observations a WHERE a.trade_date=u0.trade_date AND a.code=u0.code LIMIT 1) WHEN research='TPR_V1' THEN (SELECT t.market_pattern FROM trend_pullback_reversal_observations t WHERE t.trade_date=u0.trade_date AND t.code=u0.code LIMIT 1) END,'UNKNOWN') market_pattern FROM u0),s AS(SELECT research,COUNT(*)::int candidates,COUNT(result_5d)::int completed_5d,COUNT(DISTINCT code)FILTER(WHERE result_5d IS NOT NULL)::int codes,COUNT(DISTINCT trade_date)FILTER(WHERE result_5d IS NOT NULL)::int dates,COUNT(DISTINCT TO_CHAR(trade_date,'YYYY-MM'))FILTER(WHERE result_5d IS NOT NULL)::int months,COUNT(DISTINCT market_pattern)FILTER(WHERE result_5d IS NOT NULL AND market_pattern<>'UNKNOWN')::int regimes,ROUND(AVG(result_5d),4)avg5,ROUND(PERCENTILE_CONT(.5)WITHIN GROUP(ORDER BY result_5d)::numeric,4)median5,ROUND(100.0*COUNT(*)FILTER(WHERE result_5d>0)/NULLIF(COUNT(result_5d),0),2)positive5 FROM u GROUP BY research) SELECT *,CASE WHEN completed_5d>=50 AND codes>=30 AND dates>=15 AND months>=2 AND regimes>=2 AND avg5>=1 AND median5>=0.5 AND positive5>=60 THEN 'VALIDATED' WHEN completed_5d>=20 AND codes>=15 AND dates>=8 AND months>=2 AND avg5>0 AND median5>0 AND positive5>=55 THEN 'PROMISING' ELSE 'COLLECTING' END validation_status,ROUND((LEAST(completed_5d,50)/50.0*20 + LEAST(codes,30)/30.0*15 + LEAST(dates,15)/15.0*10 + LEAST(months,2)/2.0*10 + LEAST(regimes,2)/2.0*10 + GREATEST(LEAST(COALESCE(avg5,0),2),0)/2.0*15 + GREATEST(LEAST(COALESCE(median5,0),1),0)*10 + GREATEST(LEAST(COALESCE(positive5,0)-50,15),0)/15.0*10)::numeric,1) research_score FROM s ORDER BY research_score DESC,research`),
pool.query(`WITH u AS(${union}),g AS(SELECT trade_date,code,ARRAY_AGG(DISTINCT research ORDER BY research) researches,COUNT(DISTINCT research)::int research_count FROM u GROUP BY trade_date,code HAVING COUNT(DISTINCT research)>=2) SELECT g.trade_date,g.code,COALESCE(d.name,g.code)name,g.researches,g.research_count FROM g LEFT JOIN LATERAL(SELECT name FROM daily_stock_results d WHERE d.code=g.code AND d.date::date=g.trade_date ORDER BY d.created_at DESC LIMIT 1)d ON true ORDER BY g.trade_date DESC,g.research_count DESC LIMIT 100`),
pool.query(`WITH u AS(${union}) SELECT u.trade_date,u.code,COALESCE(d.name,u.code)name,u.research,u.result_1d,u.result_3d,u.result_5d FROM u LEFT JOIN LATERAL(SELECT name FROM daily_stock_results d WHERE d.code=u.code AND d.date::date=u.trade_date ORDER BY d.created_at DESC LIMIT 1)d ON true ORDER BY u.trade_date DESC,u.code,u.research LIMIT 100`)
]);return NextResponse.json({success:true,summary:summary.rows,overlaps:overlaps.rows,recent:recent.rows},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error("Research lab API error:",e);return NextResponse.json({success:false,error:"Research Lab data is unavailable"},{status:500})}}