import { randomUUID } from "node:crypto";
export const RunnerState = Object.freeze({ PREFLIGHT:"PREFLIGHT", READY_FOR_ACTIVATION:"READY_FOR_ACTIVATION", ROTATE:"ROTATE", DIRECT_AUTH:"DIRECT_AUTH", DIRECT_IDENTITY_CHECK:"DIRECT_IDENTITY_CHECK", POOLER_AUTH:"POOLER_AUTH", POOLER_IDENTITY_CHECK:"POOLER_IDENTITY_CHECK", VERCEL_REGISTER:"VERCEL_REGISTER", VERIFY_ENV_METADATA:"VERIFY_ENV_METADATA", CLEANUP:"CLEANUP", HOLD:"HOLD", DONE:"DONE", ABORTED:"ABORTED" });
export const VercelRecoveryObservation=Object.freeze({PRESENT_EXPECTED_METADATA:"PRESENT_EXPECTED_METADATA",ABSENT:"ABSENT",MISMATCH:"MISMATCH",UNKNOWN:"UNKNOWN"});
export const MAX_RECOVERY_HOLD_MS=15*60*1000;
export const Classification = Object.freeze({
  ROTATION_FAILED:"ROTATION_FAILED", DIRECT_SUCCESS:"DIRECT_SUCCESS", DIRECT_AUTH_FAILED:"DIRECT_AUTH_FAILED", DIRECT_NETWORK_FAILED:"DIRECT_NETWORK_FAILED", DIRECT_TLS_FAILED:"DIRECT_TLS_FAILED", DIRECT_TIMEOUT:"DIRECT_TIMEOUT", DIRECT_IDENTITY_MISMATCH:"DIRECT_IDENTITY_MISMATCH", DIRECT_ROLLBACK_FAILED:"DIRECT_ROLLBACK_FAILED",
  POOLER_SUCCESS:"POOLER_SUCCESS", POOLER_AUTH_FAILED:"POOLER_AUTH_FAILED", POOLER_NETWORK_FAILED:"POOLER_NETWORK_FAILED", POOLER_TLS_FAILED:"POOLER_TLS_FAILED", POOLER_TIMEOUT:"POOLER_TIMEOUT", POOLER_IDENTITY_MISMATCH:"POOLER_IDENTITY_MISMATCH", POOLER_ROLLBACK_FAILED:"POOLER_ROLLBACK_FAILED",
  VERCEL_AUTH_FAILED:"VERCEL_AUTH_FAILED", VERCEL_PROJECT_MISMATCH:"VERCEL_PROJECT_MISMATCH", VERCEL_ENV_ALREADY_EXISTS:"VERCEL_ENV_ALREADY_EXISTS", VERCEL_REGISTRATION_FAILED:"VERCEL_REGISTRATION_FAILED", VERCEL_METADATA_VERIFY_FAILED:"VERCEL_METADATA_VERIFY_FAILED", UNKNOWN_SAFE_FAILURE:"UNKNOWN_SAFE_FAILURE"
});
const NEXT=Object.freeze({PREFLIGHT:"READY_FOR_ACTIVATION",READY_FOR_ACTIVATION:"ROTATE",ROTATE:"DIRECT_AUTH",DIRECT_AUTH:"DIRECT_IDENTITY_CHECK",DIRECT_IDENTITY_CHECK:"POOLER_AUTH",POOLER_AUTH:"POOLER_IDENTITY_CHECK",POOLER_IDENTITY_CHECK:"VERCEL_REGISTER",VERCEL_REGISTER:"VERIFY_ENV_METADATA",VERIFY_ENV_METADATA:"CLEANUP",CLEANUP:"DONE"});
export class RunnerV2Error extends Error { constructor(code){super(code);this.name="RunnerV2Error";this.code=code;} }
class SecretVault { #secret; adopt(secret){if(this.#secret)throw new RunnerV2Error("SECRET_ALREADY_HELD");if(!Buffer.isBuffer(secret)||!secret.length)throw new RunnerV2Error("INVALID_SECRET_BUFFER");this.#secret=secret;} use(fn){if(!this.#secret)throw new RunnerV2Error("SECRET_NOT_HELD");return fn(this.#secret);} destroy(){this.#secret?.fill(0);this.#secret=undefined;} get held(){return Boolean(this.#secret);} }
const SAFE=new Set(["type","from","to","code","attempt"]);
const safeEvent=(value)=>Object.freeze(Object.fromEntries(Object.entries(value).filter(([key])=>SAFE.has(key))));
export class ForwardRotationRunnerV2 {
  #state=RunnerState.PREFLIGHT; #vault=new SecretVault(); #adapters; #events=[]; #attempts={rotation:0,direct:0,pooler:0,vercel:0}; #resumeState; #keepalive; #passes=new Set(); #runId; #registrationAttemptId; #recoveryKind; #recoveryObservation; #holdTimer; #maxRecoveryHoldMs; #vercelVerified=false; #terminalClassification;
  constructor({adapters,runId=randomUUID(),maxRecoveryHoldMs=MAX_RECOVERY_HOLD_MS}){if(typeof runId!=="string"||!runId)throw new RunnerV2Error("INVALID_RUN_ID");if(!Number.isSafeInteger(maxRecoveryHoldMs)||maxRecoveryHoldMs<1||maxRecoveryHoldMs>MAX_RECOVERY_HOLD_MS)throw new RunnerV2Error("INVALID_RECOVERY_HOLD_LIMIT");this.#adapters=Object.freeze({...adapters});this.#runId=runId;this.#maxRecoveryHoldMs=maxRecoveryHoldMs;}
  get status(){return Object.freeze({state:this.#state,credentialHeld:this.#vault.held,attempts:Object.freeze({...this.#attempts}),runId:this.#runId,registrationAttemptId:this.#registrationAttemptId,recoveryKind:this.#recoveryKind,recoveryObservation:this.#recoveryObservation,terminalClassification:this.#terminalClassification});}
  get events(){return Object.freeze(this.#events.map(event=>({...event})));}
  #record(type,fields={}){this.#events.push(safeEvent({type,...fields}));}
  #expect(state){if(this.#state!==state)throw new RunnerV2Error("INVALID_STATE");}
  #advance(){const from=this.#state,to=NEXT[from];if(!to)throw new RunnerV2Error("UNAUTHORIZED_TRANSITION");this.#state=to;this.#record("transition",{from,to});}
  #attempt(kind){if(this.#attempts[kind]>=1)throw new RunnerV2Error(`DUPLICATE_${kind.toUpperCase()}_ATTEMPT`);this.#attempts[kind]++;this.#record("attempt",{code:kind.toUpperCase(),attempt:1});}
  #fail(code){const from=this.#state;this.#resumeState=undefined;this.#state=RunnerState.HOLD;this.#record("hold",{from,to:RunnerState.HOLD,code});return false;}
  async preflight(){this.#expect(RunnerState.PREFLIGHT);if(await this.#adapters.preflight()!==true)return this.#fail("PREFLIGHT_FAILED");this.#advance();return true;}
  async rotate({secretFactory}){this.#expect(RunnerState.READY_FOR_ACTIVATION);this.#attempt("rotation");const secret=secretFactory();this.#vault.adopt(secret);this.#advance();try{const result=await this.#vault.use(value=>this.#adapters.rotate(value));if(result!==true)return this.#fail(result?.classification??"ROTATION_FAILED");this.#passes.add("rotation");this.#advance();return true;}catch{return this.#fail("ROTATION_FAILED");}}
  directAuth(){return this.#authenticate("direct",RunnerState.DIRECT_AUTH,"DIRECT_AUTH_FAILED");}
  async poolerAuth(){if(!this.#passes.has("direct_identity")||!this.#passes.has("direct_rollback"))throw new RunnerV2Error("DIRECT_NOT_COMPLETE");return this.#authenticate("pooler",RunnerState.POOLER_AUTH,"POOLER_AUTH_FAILED");}
  async #authenticate(kind,state,fallback){this.#expect(state);this.#attempt(kind);try{const result=await this.#vault.use(secret=>this.#adapters[`${kind}Auth`](secret));if(result?.ok!==true)return this.#fail(result?.classification??fallback);this.#passes.add(`${kind}_auth`);this.#advance();return true;}catch{return this.#fail(fallback);}}
  directIdentityCheck(){return this.#identity("direct",RunnerState.DIRECT_IDENTITY_CHECK,"DIRECT_IDENTITY_MISMATCH");}
  poolerIdentityCheck(){return this.#identity("pooler",RunnerState.POOLER_IDENTITY_CHECK,"POOLER_IDENTITY_MISMATCH");}
  async #identity(kind,state,fallback){this.#expect(state);try{const result=await this.#vault.use(secret=>this.#adapters[`${kind}Identity`](secret));if(result?.ok!==true||result?.rollback!==true)return this.#fail(result?.classification??fallback);this.#passes.add(`${kind}_identity`);this.#passes.add(`${kind}_rollback`);this.#advance();return true;}catch{return this.#fail(fallback);}}
  async vercelRegister(){this.#expect(RunnerState.VERCEL_REGISTER);this.#attempt("vercel");this.#registrationAttemptId=randomUUID();const required=["rotation","direct_auth","direct_identity","direct_rollback","pooler_auth","pooler_identity","pooler_rollback"];if(!required.every(pass=>this.#passes.has(pass)))throw new RunnerV2Error("PREREQUISITES_NOT_MET");try{const result=await this.#vault.use(secret=>this.#adapters.vercelRegister(secret));if(result!==true)return this.#enterVercelRecovery("REGISTRATION_UNCERTAIN",result?.classification??"VERCEL_REGISTRATION_FAILED");this.#advance();return true;}catch{return this.#enterVercelRecovery("REGISTRATION_UNCERTAIN","VERCEL_REGISTRATION_FAILED");}}
  async verifyEnvMetadata(){this.#expect(RunnerState.VERIFY_ENV_METADATA);try{if(await this.#adapters.verifyEnvMetadata()!==true)throw 0;this.#vercelVerified=true;this.#advance();return true;}catch{return this.#enterVercelRecovery("METADATA_VERIFICATION_FAILED","VERCEL_METADATA_VERIFY_FAILED");}}
  #enterVercelRecovery(kind,code){this.#recoveryKind=kind;this.#recoveryObservation=undefined;const result=this.#fail(code);this.#holdTimer=setTimeout(()=>{void this.abort("RECOVERY_HOLD_EXPIRED");},this.#maxRecoveryHoldMs);this.#holdTimer.unref?.();return result;}
  observeVercelRecovery(classification){if(this.#state!==RunnerState.HOLD||!this.#recoveryKind)throw new RunnerV2Error("VERCEL_RECOVERY_NOT_ACTIVE");if(!Object.values(VercelRecoveryObservation).includes(classification))throw new RunnerV2Error("INVALID_RECOVERY_OBSERVATION");this.#recoveryObservation=classification;this.#record("recovery_observation",{code:classification});return Object.freeze({runId:this.#runId,registrationAttemptId:this.#registrationAttemptId,recoveryKind:this.#recoveryKind,observation:classification,currentState:RunnerState.HOLD});}
  async completeVercelRecovery(binding){if(this.#state!==RunnerState.HOLD||this.#recoveryObservation!==VercelRecoveryObservation.PRESENT_EXPECTED_METADATA)throw new RunnerV2Error("RECOVERY_COMPLETION_REJECTED");if(binding?.runId!==this.#runId||binding?.registrationAttemptId!==this.#registrationAttemptId||binding?.observation!==this.#recoveryObservation||binding?.currentState!==RunnerState.HOLD)throw new RunnerV2Error("RECOVERY_IDENTITY_MISMATCH");this.#record("recovery_authorized",{code:"PRESENT_EXPECTED_METADATA"});this.#vercelVerified=true;this.#recoveryKind=undefined;return this.cleanup();}
  hold(code="OPERATOR_HOLD"){if(this.#state===RunnerState.HOLD)return;this.#resumeState=this.#state;const from=this.#state;this.#state=RunnerState.HOLD;this.#record("hold",{from,to:RunnerState.HOLD,code});}
  resume({authorized=false}={}){if(!authorized||this.#state!==RunnerState.HOLD||!this.#resumeState)throw new RunnerV2Error("RESUME_NOT_AUTHORIZED");this.#state=this.#resumeState;this.#resumeState=undefined;}
  maintainHoldAcrossInputEof(input){this.#expect(RunnerState.HOLD);input.once("end",()=>this.#record("stdin_eof_ignored"));this.#keepalive??=setInterval(()=>{},2**30);}
  async cleanup(){if(this.#state===RunnerState.DONE)return;if(this.#state===RunnerState.HOLD&&this.#recoveryKind)throw new RunnerV2Error("RECOVERY_HOLD_REQUIRES_SIGNED_COMPLETION_OR_ABORT");const from=this.#state;this.#state=RunnerState.CLEANUP;this.#record("transition",{from,to:RunnerState.CLEANUP});try{await this.#adapters.cleanup?.();}catch{this.#record("cleanup_failed",{code:"CLEANUP_FAILED"});}finally{this.#vault.destroy();this.#clearTimers();this.#advance();}}
  async abort(code="OPERATOR_ABORT"){if(this.#state===RunnerState.DONE||this.#state===RunnerState.ABORTED)return;this.#vault.destroy();this.#clearTimers();try{await this.#adapters.cleanup?.();}catch{}this.#terminalClassification=this.#passes.has("rotation")&&!this.#vercelVerified?"ABORTED_ROTATED_CREDENTIAL_MAY_BE_UNPROVISIONED":code;this.#state=RunnerState.ABORTED;this.#record("abort",{code:this.#terminalClassification});}
  #clearTimers(){if(this.#keepalive)clearInterval(this.#keepalive);if(this.#holdTimer)clearTimeout(this.#holdTimer);this.#keepalive=undefined;this.#holdTimer=undefined;}
}
