using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Text;
using Microsoft.Win32.SafeHandles;

internal static class TrustedWindowsKeyReader
{
    const int MaxKey=16*1024;
    const uint OwnerSecurityInformation=0x1,DaclSecurityInformation=0x4,SeFileObject=1;
    const uint GenericRead=0x80000000,ReadControl=0x00020000,ShareRead=1,OpenExisting=3,OpenReparsePoint=0x00200000,BackupSemantics=0x02000000;
    [StructLayout(LayoutKind.Sequential)] struct Info { public uint Attributes; public System.Runtime.InteropServices.ComTypes.FILETIME CreationTime,LastAccessTime,LastWriteTime; public uint VolumeSerialNumber,FileSizeHigh,FileSizeLow,NumberOfLinks,FileIndexHigh,FileIndexLow; }
    [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern SafeFileHandle CreateFile(string name,uint access,uint share,IntPtr security,uint creation,uint flags,IntPtr template);
    [DllImport("kernel32.dll",SetLastError=true)] static extern bool GetFileInformationByHandle(SafeFileHandle handle,out Info info);
    [DllImport("kernel32.dll",SetLastError=true)] static extern bool ReadFile(SafeFileHandle handle,IntPtr buffer,uint bytesToRead,out uint bytesRead,IntPtr overlapped);
    [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern uint GetFinalPathNameByHandle(SafeFileHandle handle,StringBuilder path,uint length,uint flags);
    [DllImport("advapi32.dll",SetLastError=true)] static extern uint GetSecurityInfo(SafeFileHandle handle,uint objectType,uint securityInfo,out IntPtr owner,out IntPtr group,out IntPtr dacl,out IntPtr sacl,out IntPtr descriptor);
    [DllImport("advapi32.dll")] static extern uint GetSecurityDescriptorLength(IntPtr descriptor);
    [DllImport("kernel32.dll")] static extern IntPtr LocalFree(IntPtr memory);

    static string J(string value){var b=new StringBuilder("\"");foreach(char c in value){if(c=='\\'||c=='"')b.Append('\\').Append(c);else if(c<32)b.Append("\\u").Append(((int)c).ToString("x4"));else b.Append(c);}return b.Append('"').ToString();}
    static ulong FileId(Info value){return ((ulong)value.FileIndexHigh<<32)|value.FileIndexLow;}
    static long Size(Info value){return ((long)value.FileSizeHigh<<32)|value.FileSizeLow;}
    static long WriteTime(Info value){return ((long)(uint)value.LastWriteTime.dwHighDateTime<<32)|(uint)value.LastWriteTime.dwLowDateTime;}
    static FileSecurity SecurityFromHandle(SafeFileHandle handle){IntPtr owner,group,dacl,sacl,descriptor;uint result=GetSecurityInfo(handle,SeFileObject,OwnerSecurityInformation|DaclSecurityInformation,out owner,out group,out dacl,out sacl,out descriptor);if(result!=0||descriptor==IntPtr.Zero)throw new InvalidOperationException("SECURITY_DESCRIPTOR_UNAVAILABLE");try{uint length=GetSecurityDescriptorLength(descriptor);if(length==0||length>65536)throw new InvalidOperationException("SECURITY_DESCRIPTOR_INVALID");byte[] bytes=new byte[length];Marshal.Copy(descriptor,bytes,0,(int)length);var security=new FileSecurity();security.SetSecurityDescriptorBinaryForm(bytes);return security;}finally{LocalFree(descriptor);}}
    static bool HasAll(FileSystemRights value,FileSystemRights required){return (value&required)==required;}
    static bool HasAny(FileSystemRights value,FileSystemRights required){return (value&required)!=0;}
    static bool Dangerous(FileSystemRights value){
        // WriteData/CreateFiles and AppendData/CreateDirectories are enum aliases.
        const FileSystemRights dangerous=FileSystemRights.WriteData|FileSystemRights.AppendData|FileSystemRights.WriteExtendedAttributes|FileSystemRights.WriteAttributes|FileSystemRights.Delete|FileSystemRights.DeleteSubdirectoriesAndFiles|FileSystemRights.ChangePermissions|FileSystemRights.TakeOwnership;
        return HasAny(value,dangerous)||HasAll(value,FileSystemRights.Modify)||HasAll(value,FileSystemRights.FullControl);
    }
    static FileSystemRights RequiredRunnerRights(bool directory){return (directory?FileSystemRights.ReadAndExecute:FileSystemRights.Read)|FileSystemRights.Synchronize;}
    static bool FixtureRightsAccepted(string objectType,string principal,string rightsName){FileSystemRights rights=(FileSystemRights)Enum.Parse(typeof(FileSystemRights),rightsName,false);bool directory=objectType=="directory";if(!directory&&objectType!="key")return false;return principal=="runner"?!Dangerous(rights)&&HasAll(rights,RequiredRunnerRights(directory)):!Dangerous(rights);}
    static void ValidateAcl(FileSecurity security,string runner,string provisioner,bool directory){string owner=((SecurityIdentifier)security.GetOwner(typeof(SecurityIdentifier))).Value;var owners=new HashSet<string>(StringComparer.OrdinalIgnoreCase){"S-1-5-18",provisioner};if(!owners.Contains(owner))throw new InvalidOperationException("OWNER_REJECTED");if(!security.AreAccessRulesProtected)throw new InvalidOperationException("DACL_REJECTED");bool runnerSeen=false,systemFull=false,provisionerFull=false;foreach(FileSystemAccessRule rule in security.GetAccessRules(true,true,typeof(SecurityIdentifier))){string sid=rule.IdentityReference.Value;if(rule.IsInherited)throw new InvalidOperationException("INHERITED_ACE_REJECTED");if(sid=="S-1-1-0")throw new InvalidOperationException("EVERYONE_REJECTED");bool write=Dangerous(rule.FileSystemRights);if((sid=="S-1-5-32-545"||sid=="S-1-5-11")&&write)throw new InvalidOperationException("BROAD_WRITE_REJECTED");if(String.Equals(sid,runner,StringComparison.OrdinalIgnoreCase)){runnerSeen=true;if(write||!HasAll(rule.FileSystemRights,RequiredRunnerRights(directory)))throw new InvalidOperationException("RUNNER_ACL_REJECTED");}else if(sid=="S-1-5-18")systemFull|=HasAll(rule.FileSystemRights,FileSystemRights.FullControl);else if(String.Equals(sid,provisioner,StringComparison.OrdinalIgnoreCase))provisionerFull|=HasAll(rule.FileSystemRights,FileSystemRights.FullControl);else if(write)throw new InvalidOperationException("UNEXPECTED_WRITE_REJECTED");}if(!runnerSeen||!systemFull||!provisionerFull)throw new InvalidOperationException("REQUIRED_ACL_MISSING");}
    static void ValidateComponents(string root,string target){string rootFull=Path.GetFullPath(root),targetFull=Path.GetFullPath(target);if(targetFull.StartsWith("\\\\")||!targetFull.StartsWith(rootFull+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)||targetFull.IndexOf("..",StringComparison.Ordinal)>=0)throw new InvalidOperationException("PATH_REJECTED");var parts=targetFull.Substring(Path.GetPathRoot(targetFull).Length).Split(Path.DirectorySeparatorChar);string current=Path.GetPathRoot(targetFull);foreach(string part in parts){current=Path.Combine(current,part);using(SafeFileHandle h=CreateFile(current,ReadControl,7,IntPtr.Zero,OpenExisting,OpenReparsePoint|BackupSemantics,IntPtr.Zero)){if(h.IsInvalid)throw new InvalidOperationException("COMPONENT_OPEN_FAILED");Info i;if(!GetFileInformationByHandle(h,out i)||(i.Attributes&0x400)!=0)throw new InvalidOperationException("REPARSE_REJECTED");}}}
    static byte[] ReadExact(SafeFileHandle handle,long expected){if(expected<=0||expected>MaxKey)throw new InvalidOperationException("SIZE_REJECTED");var bounded=new byte[MaxKey+1];var pinned=GCHandle.Alloc(bounded,GCHandleType.Pinned);try{int offset=0;while(offset<bounded.Length){uint read;if(!ReadFile(handle,IntPtr.Add(pinned.AddrOfPinnedObject(),offset),(uint)(bounded.Length-offset),out read,IntPtr.Zero))throw new InvalidOperationException("READ_FAILED");if(read==0)break;offset+=(int)read;}if(offset!=expected||offset>MaxKey)throw new InvalidOperationException("READ_LENGTH_MISMATCH");var output=new byte[offset];Buffer.BlockCopy(bounded,0,output,0,offset);return output;}finally{pinned.Free();}}
    static void WriteFrame(byte[] metadata,byte[] key){var stdout=Console.OpenStandardOutput();byte[] magic=Encoding.ASCII.GetBytes("SXKEYV2\0");stdout.Write(magic,0,magic.Length);var lengths=new byte[8];Array.Copy(BitConverter.GetBytes(metadata.Length),0,lengths,0,4);Array.Copy(BitConverter.GetBytes(key.Length),0,lengths,4,4);stdout.Write(lengths,0,8);stdout.Write(metadata,0,metadata.Length);stdout.Write(key,0,key.Length);stdout.Flush();}
    static void Execute(string target,string root,string runner,string provisioner){ValidateComponents(root,target);using(SafeFileHandle rootHandle=CreateFile(root,ReadControl,7,IntPtr.Zero,OpenExisting,OpenReparsePoint|BackupSemantics,IntPtr.Zero)){if(rootHandle.IsInvalid)throw new InvalidOperationException("ROOT_OPEN_FAILED");ValidateAcl(SecurityFromHandle(rootHandle),runner,provisioner,true);}const uint flags=OpenReparsePoint;using(SafeFileHandle handle=CreateFile(target,GenericRead|ReadControl,ShareRead,IntPtr.Zero,OpenExisting,flags,IntPtr.Zero)){if(handle.IsInvalid)throw new InvalidOperationException("KEY_OPEN_FAILED");Info before;if(!GetFileInformationByHandle(handle,out before)||(before.Attributes&0x10)!=0||(before.Attributes&0x400)!=0)throw new InvalidOperationException("FILE_TYPE_REJECTED");var final=new StringBuilder(32768);uint length=GetFinalPathNameByHandle(handle,final,(uint)final.Capacity,0);if(length==0||length>=final.Capacity)throw new InvalidOperationException("FINAL_PATH_UNAVAILABLE");string normalizedFinal=final.ToString().Replace("\\\\?\\","");if(!String.Equals(Path.GetFullPath(target),normalizedFinal,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("FINAL_PATH_MISMATCH");FileSecurity securityBefore=SecurityFromHandle(handle);ValidateAcl(securityBefore,runner,provisioner,false);byte[] key=ReadExact(handle,Size(before));Info after;if(!GetFileInformationByHandle(handle,out after)||FileId(before)!=FileId(after)||before.VolumeSerialNumber!=after.VolumeSerialNumber||Size(before)!=Size(after)||WriteTime(before)!=WriteTime(after))throw new InvalidOperationException("IDENTITY_CHANGED");FileSecurity securityAfter=SecurityFromHandle(handle);ValidateAcl(securityAfter,runner,provisioner,false);if(!StructuralComparisons.StructuralEqualityComparer.Equals(securityBefore.GetSecurityDescriptorBinaryForm(),securityAfter.GetSecurityDescriptorBinaryForm()))throw new InvalidOperationException("ACL_CHANGED");string metadata="{\"sameHandle\":true,\"volumeSerial\":"+J(before.VolumeSerialNumber.ToString("x8"))+",\"fileId\":"+J(FileId(before).ToString("x16")) +",\"size\":"+Size(before)+",\"ownerPresent\":true,\"daclPresent\":true,\"reparseChecked\":true}";WriteFrame(Encoding.UTF8.GetBytes(metadata),key);}}
    public static int Main(string[] args){try{if(args.Length==4&&args[0]=="acl-rights-fixture")return FixtureRightsAccepted(args[1],args[2],args[3])?0:31;string target,root,runner,provisioner;if(args.Length==1&&args[0]=="read-production"){string programData=Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);root=Path.Combine(programData,"SignalX","runner-v2","trust");target=Path.Combine(root,"operator-public.pem");runner=WindowsIdentity.GetCurrent().User.Value;provisioner="S-1-5-32-544";}else if(args.Length==5&&args[0]=="read-fixture"){target=args[1];root=args[2];runner=args[3];provisioner=args[4];}else throw new InvalidOperationException("REQUEST_REJECTED");Execute(target,root,runner,provisioner);return 0;}catch(InvalidOperationException error){return error.Message=="OWNER_REJECTED"?21:2;}catch{return 2;}}
}
