import assert from "node:assert/strict";
import { createSign, generateKeyPairSync } from "node:crypto";
import test from "node:test";
import { RunnerState } from "../scripts/runner-v2/state-machine.mjs";
import { TARGET_ROLE, VERCEL_TARGET } from "../scripts/runner-v2/production-adapters.mjs";
import { canonicalActivationManifest, createProductionOperatorAuthorizer, PRODUCTION_IDENTITY } from "../scripts/runner-v2/operator-authorization.mjs";
import { operatorPublicKeyFingerprint, validateTrustedOperatorPublicKey } from "../scripts/runner-v2/trusted-operator-key.mjs";
import { createPrivilegedClientFactory } from "../scripts/runner-v2/privileged-client-factory.mjs";

function keys(type="rsa",modulusLength=3072){const pair=type==="rsa"?generateKeyPairSync("rsa",{modulusLength}):generateKeyPairSync("ec",{namedCurve:"P-256"});return{...pair,pem:pair.publicKey.export({type:"spki",format:"pem"})};}
function signed(overrides={}){const key=keys(),now=2_000_000_000_000,manifest={command:"ACTIVATE",...PRODUCTION_IDENTITY,currentState:RunnerState.PREFLIGHT,nonce:"hardening-nonce-001",expiresAt:now+60_000,...overrides};const signer=createSign("SHA256");signer.update(canonicalActivationManifest(manifest));signer.end();return{manifest,signature:signer.sign(key.privateKey),pem:key.pem,now};}
async function accepted(fixture){const authorize=createProductionOperatorAuthorizer({trustedPublicKey:fixture.pem,approvedFingerprint:operatorPublicKeyFingerprint(fixture.pem),now:()=>fixture.now});return authorize({command:"ACTIVATE",authorization:{manifest:fixture.manifest,signature:fixture.signature},currentState:RunnerState.PREFLIGHT});}

test("manifest accepts exact targetVariable",async()=>assert.equal(await accepted(signed()),true));
for(const [name,value] of [["missing",undefined],["wrong","DATABASE_URL"],["case","signalx_entitlements_database_url"],["whitespace",` ${VERCEL_TARGET.variable}`]])test(`manifest rejects ${name} targetVariable`,async()=>assert.equal(await accepted(signed({targetVariable:value})),false));
test("tampered targetVariable invalidates signature",async()=>{const fixture=signed();fixture.manifest={...fixture.manifest,targetVariable:"DATABASE_URL"};assert.equal(await accepted(fixture),false);});

test("valid RSA 3072 SPKI and deterministic fingerprint are accepted",()=>{const {pem}=keys();const one=operatorPublicKeyFingerprint(pem),two=operatorPublicKeyFingerprint(pem);assert.equal(one,two);assert.match(one,/^sha256:[0-9a-f]{64}$/);assert.equal(validateTrustedOperatorPublicKey({pem,approvedFingerprint:one}).fingerprint,one);});
test("RSA below 3072 is rejected",()=>{const {pem}=keys("rsa",2048);assert.throws(()=>operatorPublicKeyFingerprint(pem),/TRUSTED_RSA_KEY_TOO_WEAK/);});
test("EC public key is rejected",()=>{const {pem}=keys("ec");assert.throws(()=>operatorPublicKeyFingerprint(pem),/TRUSTED_KEY_MUST_BE_RSA/);});
test("malformed and missing public keys are rejected",()=>{assert.throws(()=>operatorPublicKeyFingerprint("-----BEGIN PUBLIC KEY-----\nbad\n-----END PUBLIC KEY-----"),/MALFORMED/);assert.throws(()=>createProductionOperatorAuthorizer({}),/TRUSTED_PUBLIC_KEY_REQUIRED/);});
test("fingerprint mismatch fails closed",()=>{const {pem}=keys();assert.throws(()=>validateTrustedOperatorPublicKey({pem,approvedFingerprint:"sha256:"+"0".repeat(64)}),/FINGERPRINT_MISMATCH/);});

function privilegedFixture(){let constructions=0,connects=0,ends=0;let credential;class Client{constructor(config){constructions++;assert.deepEqual(config.ssl,{rejectUnauthorized:true});assert.equal(config.connectionTimeoutMillis,10_000);}async connect(){connects++;}async query(){return true;}async end(){ends++;}}const provider=async({targetRole})=>{assert.equal(targetRole,TARGET_ROLE);credential={host:"fixed-admin-host.invalid",port:5432,database:"postgres",username:"approved-operator",password:Buffer.from("fixture-credential")};return credential;};return{factory:createPrivilegedClientFactory({credentialProvider:provider,ClientClass:Client}),counts:()=>({constructions,connects,ends}),credential:()=>credential};}
test("privileged factory accepts only approved target, uses TLS once, no retry, and zeroizes on cleanup",async()=>{const fx=privilegedFixture(),client=fx.factory({targetRole:TARGET_ROLE});await client.connect();await client.query("fixed-by-rotation-driver");await client.end();assert.deepEqual(fx.counts(),{constructions:1,connects:1,ends:1});assert.ok(fx.credential().password.every(byte=>byte===0));assert.throws(()=>fx.factory({targetRole:TARGET_ROLE}),/DUPLICATE_PRIVILEGED_CONNECTION_ATTEMPT/);});
test("privileged factory rejects postgres and other roles before credential access",()=>{let calls=0;const factory=createPrivilegedClientFactory({credentialProvider:async()=>{calls++;},ClientClass:class{}});assert.throws(()=>factory({targetRole:"postgres"}),/ROTATION_TARGET_REJECTED/);assert.throws(()=>factory({targetRole:"other"}),/ROTATION_TARGET_REJECTED/);assert.equal(calls,0);});
test("privileged factory does not read DATABASE_URL or leak fixture secret",async()=>{const before=process.env.DATABASE_URL,out=[],err=[],oldOut=process.stdout.write,oldErr=process.stderr.write;process.stdout.write=x=>(out.push(String(x)),true);process.stderr.write=x=>(err.push(String(x)),true);try{const fx=privilegedFixture(),client=fx.factory({targetRole:TARGET_ROLE});await client.connect();await client.end();}finally{process.stdout.write=oldOut;process.stderr.write=oldErr;}assert.equal(process.env.DATABASE_URL,before);assert.ok(!out.join("").includes("fixture-credential")&&!err.join("").includes("fixture-credential"));});
