import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { readdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { Classification, ForwardRotationRunnerV2, RunnerState } from "../scripts/runner-v2/state-machine.mjs";
import { OperatorControl } from "../scripts/runner-v2/operator-control.mjs";
import { createProductionAdapters, DIRECT_CONFIG, IDENTITY_SQL, POOLER_CONFIG, TARGET_ROLE, VERCEL_TARGET } from "../scripts/runner-v2/production-adapters.mjs";
const SECRET_TEXT="dummy-secret-only";
function fixture(fail={}){
 const calls=[];let owned;
 const session=kind=>({execute:async sql=>{calls.push(`${kind}:sql:${sql}`);if(fail[`${kind}Rollback`]&&sql==="ROLLBACK;")throw Error("rollback");if(sql.startsWith("SELECT"))return fail[`${kind}Mismatch`]?{currentUser:"wrong",sessionUser:TARGET_ROLE,currentDatabase:"postgres"}:{currentUser:TARGET_ROLE,sessionUser:TARGET_ROLE,currentDatabase:"postgres"};},close:async()=>calls.push(`${kind}:close`)});
 const driver=kind=>({authenticate:async config=>{calls.push(`${kind}:auth`);assert.ok(Buffer.isBuffer(config.password));assert.deepEqual({...config,password:undefined},{...(kind==="direct"?DIRECT_CONFIG:POOLER_CONFIG),password:undefined});if(fail[`${kind}Auth`])throw Object.assign(Error("safe"),{code:"28P01"});if(fail[`${kind}Network`])throw Object.assign(Error("network"),{code:"ECONNREFUSED"});},open:async()=>{calls.push(`${kind}:open`);return session(kind);}});
 const adapters=createProductionAdapters({rotationDriver:{rotateRolePassword:async({role,password})=>{calls.push("rotate");assert.equal(role,TARGET_ROLE);assert.ok(Buffer.isBuffer(password));return !fail.rotation;}},directDriver:driver("direct"),poolerDriver:driver("pooler"),vercelDriver:{registerSensitiveFromStdin:async({target,stdin})=>{calls.push("vercel");assert.deepEqual(target,VERCEL_TARGET);assert.ok(Buffer.isBuffer(stdin));return !fail.vercel;},verifyMetadata:async({target})=>{calls.push("metadata");assert.deepEqual(target,VERCEL_TARGET);return !fail.metadata;}}});
 const runner=new ForwardRotationRunnerV2({adapters});const secretFactory=()=>{owned=Buffer.from(SECRET_TEXT);return owned;};return{runner,control:new OperatorControl({runner,secretFactory,authorize:async()=>true}),calls,owned:()=>owned};
}
async function runTo(fx,last="VERIFY_ENV_METADATA"){for(const command of ["ACTIVATE","ROTATE","DIRECT_AUTH","DIRECT_IDENTITY_CHECK","POOLER_AUTH","POOLER_IDENTITY_CHECK","VERCEL_REGISTER","VERIFY_ENV_METADATA"]){const result=await fx.control.command(command);if(command===last||result!==true)return result;}}
test("complete happy path uses fixed endpoints, read-only SQL and cleanup",async()=>{const fx=fixture();assert.equal(await runTo(fx),true);assert.equal(fx.runner.status.state,RunnerState.CLEANUP);for(const kind of ["direct","pooler"])assert.deepEqual(fx.calls.filter(x=>x.startsWith(`${kind}:sql:`)).map(x=>x.slice(`${kind}:sql:`.length)),IDENTITY_SQL);await fx.control.command("CLEANUP");assert.equal(fx.runner.status.state,RunnerState.DONE);assert.ok(fx.owned().every(byte=>byte===0));});
for(const [name,fail,stop,classification] of [
 ["rotation failure",{rotation:true},"ROTATE","ROTATION_FAILED"],["Direct auth failure",{directAuth:true},"DIRECT_AUTH",Classification.DIRECT_AUTH_FAILED],["Direct network failure",{directNetwork:true},"DIRECT_AUTH",Classification.DIRECT_NETWORK_FAILED],["Direct identity mismatch",{directMismatch:true},"DIRECT_IDENTITY_CHECK",Classification.DIRECT_IDENTITY_MISMATCH],["Direct rollback failure",{directRollback:true},"DIRECT_IDENTITY_CHECK",Classification.DIRECT_ROLLBACK_FAILED],["Pooler auth failure",{poolerAuth:true},"POOLER_AUTH",Classification.POOLER_AUTH_FAILED],["Pooler network failure",{poolerNetwork:true},"POOLER_AUTH",Classification.POOLER_NETWORK_FAILED],["Pooler identity mismatch",{poolerMismatch:true},"POOLER_IDENTITY_CHECK",Classification.POOLER_IDENTITY_MISMATCH],["Pooler rollback failure",{poolerRollback:true},"POOLER_IDENTITY_CHECK",Classification.POOLER_ROLLBACK_FAILED],["Vercel registration failure",{vercel:true},"VERCEL_REGISTER","VERCEL_REGISTRATION_FAILED"],["Vercel metadata verification failure",{metadata:true},"VERIFY_ENV_METADATA",Classification.VERCEL_METADATA_VERIFY_FAILED]
])test(name,async()=>{const fx=fixture(fail);assert.equal(await runTo(fx,stop),false);assert.equal(fx.runner.status.state,RunnerState.HOLD);assert.equal(fx.runner.events.at(-1).code,classification);if(fx.runner.status.recoveryKind)await fx.runner.abort("TEST_TERMINAL_ABORT");else await fx.runner.cleanup();});
test("Direct failures block Pooler and Vercel with zero attempts",async()=>{for(const fail of [{directAuth:true},{directNetwork:true},{directMismatch:true},{directRollback:true}]){const fx=fixture(fail);await runTo(fx,fail.directMismatch||fail.directRollback?"DIRECT_IDENTITY_CHECK":"DIRECT_AUTH");assert.equal(fx.runner.status.attempts.pooler,0);assert.equal(fx.runner.status.attempts.vercel,0);assert.ok(!fx.calls.includes("pooler:auth")&&!fx.calls.includes("vercel"));await fx.runner.cleanup();}});
test("Pooler failures block Vercel with zero operations",async()=>{for(const fail of [{poolerAuth:true},{poolerNetwork:true},{poolerMismatch:true},{poolerRollback:true}]){const fx=fixture(fail);await runTo(fx,fail.poolerMismatch||fail.poolerRollback?"POOLER_IDENTITY_CHECK":"POOLER_AUTH");assert.equal(fx.runner.status.attempts.vercel,0);assert.ok(!fx.calls.includes("vercel"));await fx.runner.cleanup();}});
test("unauthorized order and duplicate dangerous attempts are rejected",async()=>{const fx=fixture();await assert.rejects(()=>fx.control.command("ROTATE"),{code:"OPERATOR_COMMAND_REJECTED"});await fx.control.command("ACTIVATE");await fx.control.command("ROTATE");await assert.rejects(()=>fx.runner.rotate({secretFactory:()=>Buffer.from("x")}),{code:"INVALID_STATE"});await fx.control.command("DIRECT_AUTH");await assert.rejects(()=>fx.runner.directAuth(),{code:"INVALID_STATE"});await fx.control.command("DIRECT_IDENTITY_CHECK");await fx.control.command("POOLER_AUTH");await assert.rejects(()=>fx.runner.poolerAuth(),{code:"INVALID_STATE"});await fx.control.command("POOLER_IDENTITY_CHECK");await fx.control.command("VERCEL_REGISTER");await assert.rejects(()=>fx.runner.vercelRegister(),{code:"INVALID_STATE"});await fx.runner.cleanup();});
test("HOLD persists across EOF and resume requires authorization",async()=>{const fx=fixture();await fx.control.command("ACTIVATE");fx.runner.hold();const input=new EventEmitter();fx.runner.maintainHoldAcrossInputEof(input);input.emit("end");assert.equal(fx.runner.status.state,RunnerState.HOLD);await assert.rejects(()=>fx.control.command("ROTATE"),{code:"HOLD_COMMAND_REJECTED"});assert.throws(()=>fx.runner.resume(),{code:"RESUME_NOT_AUTHORIZED"});await fx.control.command("RESUME",{operatorToken:"mock-only"});assert.equal(fx.runner.status.state,RunnerState.READY_FOR_ACTIVATION);await fx.runner.cleanup();});
test("operator authorizer is mandatory and rejection blocks commands",async()=>{const fx=fixture();assert.throws(()=>new OperatorControl({runner:fx.runner,secretFactory:()=>Buffer.from("x")}),{code:"OPERATOR_AUTHORIZER_REQUIRED"});const control=new OperatorControl({runner:fx.runner,secretFactory:()=>Buffer.from("x"),authorize:async()=>false});await assert.rejects(()=>control.command("ACTIVATE",{operatorToken:"bad"}),{code:"OPERATOR_NOT_AUTHORIZED"});assert.equal(fx.runner.status.state,RunnerState.PREFLIGHT);await fx.runner.cleanup();});
test("secret absent from events/stdout/stderr/temp and DATABASE_URL untouched",async()=>{const dir=await mkdtemp(join(tmpdir(),"runner-v2-test-")),before=await readdir(dir),out=[],err=[],oldOut=process.stdout.write,oldErr=process.stderr.write,oldUrl=process.env.DATABASE_URL;process.stdout.write=x=>(out.push(String(x)),true);process.stderr.write=x=>(err.push(String(x)),true);try{const fx=fixture({directNetwork:true});await runTo(fx,"DIRECT_AUTH");assert.ok(!JSON.stringify(fx.runner.events).includes(SECRET_TEXT));await fx.runner.cleanup();}finally{process.stdout.write=oldOut;process.stderr.write=oldErr;}assert.deepEqual(await readdir(dir),before);assert.equal(process.env.DATABASE_URL,oldUrl);assert.ok(!out.join("").includes(SECRET_TEXT)&&!err.join("").includes(SECRET_TEXT));await rm(dir,{recursive:true,force:true});});
test("classifications contain no credential material",()=>{assert.ok(!JSON.stringify(Classification).match(/password|postgresql:\/\//i));});
