import test,{after,before} from "node:test";
import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {generateKeyPairSync,randomUUID} from "node:crypto";
import {mkdtemp,mkdir,writeFile,rm,rename,copyFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createNativeWindowsAclInspector} from "../scripts/runner-v2/native-windows-acl-inspector.mjs";
import {createTestTrustedOperatorPublicKeyProvider} from "../scripts/runner-v2/windows-trusted-key-provider.mjs";

const windowsOnly=process.platform==="win32"?test:test.skip;
let root,trust,keyPath,helperPath,inspector,publicKey,currentPrincipal,runnerPrincipal;
const csc="C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\csc.exe";
function ps(script){const encoded=Buffer.from(script,"utf16le").toString("base64");return execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-EncodedCommand",encoded],{encoding:"utf8",windowsHide:true,timeout:15000,stdio:["ignore","pipe","pipe"]}).trim();}
function aclScript(target,isDirectory,{inheritance=false,broadWrite=false,runnerWrite=false}={}){const escaped=target.replaceAll("'","''");return `$p='${escaped}';$isDir=$${isDirectory?"true":"false"};$s=if($isDir){New-Object System.Security.AccessControl.DirectorySecurity}else{New-Object System.Security.AccessControl.FileSecurity};$s.SetAccessRuleProtection($${inheritance?"false":"true"},$false);$me=[Security.Principal.WindowsIdentity]::GetCurrent().User;$s.SetOwner($me);$inh=if($isDir){[Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit}else{[Security.AccessControl.InheritanceFlags]::None};$prop=[Security.AccessControl.PropagationFlags]::None;$allow=[Security.AccessControl.AccessControlType]::Allow;$users=New-Object Security.Principal.SecurityIdentifier('S-1-5-32-545');$system=New-Object Security.Principal.SecurityIdentifier('S-1-5-18');$read=[Security.AccessControl.FileSystemRights]::ReadAndExecute -bor [Security.AccessControl.FileSystemRights]::ReadPermissions;$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($users,$read,$inh,$prop,$allow)));$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($system,[Security.AccessControl.FileSystemRights]::FullControl,$inh,$prop,$allow)));$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($me,[Security.AccessControl.FileSystemRights]::FullControl,$inh,$prop,$allow)));${broadWrite?"$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($users,[Security.AccessControl.FileSystemRights]::Write,$inh,$prop,$allow)));":""}${runnerWrite?"$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($users,[Security.AccessControl.FileSystemRights]::Delete,$inh,$prop,$allow)));":""}if($isDir){(New-Object IO.DirectoryInfo($p)).SetAccessControl($s)}else{(New-Object IO.FileInfo($p)).SetAccessControl($s)}`;}
async function applyAcl(options={}){ps(aclScript(trust,true,options));ps(aclScript(keyPath,false,options));}
function provider(customInspector=inspector,target=keyPath){return createTestTrustedOperatorPublicKeyProvider({expectedPath:target,approvedRoot:path.dirname(target),componentBase:root,aclInspector:customInspector,runnerPrincipal,provisionerPrincipals:[currentPrincipal]});}

before(async()=>{if(process.platform!=="win32")return;root=await mkdtemp(path.join(os.tmpdir(),"signalx-runner-v2-acl-fixture-"));trust=path.join(root,"trust");await mkdir(trust);keyPath=path.join(trust,"operator-public.pem");helperPath=path.join(root,"native-acl-inspector.exe");execFileSync(csc,["/nologo","/target:exe",`/out:${helperPath}`,path.resolve("scripts/runner-v2/native-windows-acl-inspector-helper.cs")],{windowsHide:true,timeout:30000,stdio:["ignore","pipe","pipe"]});publicKey=generateKeyPairSync("rsa",{modulusLength:3072,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}}).publicKey;await writeFile(keyPath,publicKey,{encoding:"ascii"});await applyAcl();inspector=createNativeWindowsAclInspector({helperPath});const report=await inspector.inspectPath(keyPath);currentPrincipal=report.owner;runnerPrincipal=report.entries.find(entry=>entry.sid==="S-1-5-32-545")?.principal;if(!runnerPrincipal)throw new Error("FIXTURE_RUNNER_IDENTITY_UNAVAILABLE");});
after(async()=>{if(root&&path.resolve(root).startsWith(path.resolve(os.tmpdir()))&&path.basename(root).startsWith("signalx-runner-v2-acl-fixture-"))await rm(root,{recursive:true,force:true,maxRetries:3,retryDelay:50});});

windowsOnly("native valid ACL returns owner/DACL/reparse/file identity and provider accepts",async()=>{await applyAcl();const report=await inspector.inspectPath(keyPath);assert.equal(report.ownerSidPresent,true);assert.equal(report.inheritanceEnabled,false);assert.equal(report.isReparsePoint,false);assert.match(report.volumeSerial,/^[0-9a-f]{8}$/i);assert.match(report.fileId,/^[0-9a-f]{16}$/i);assert.ok(report.entries.length>=3);assert.equal(await provider()(),publicKey);});
windowsOnly("native inheritance-enabled ACL is rejected",async()=>{await applyAcl({inheritance:true});await assert.rejects(provider()(),/PUBLIC_KEY_ACL_INHERITANCE_ENABLED/);});
windowsOnly("native broad writable principal is rejected",async()=>{await applyAcl({broadWrite:true});await assert.rejects(provider()(),/PUBLIC_KEY_(BROAD_WRITE|RUNNER_WRITE)_REJECTED/);});
windowsOnly("native runner delete permission is rejected",async()=>{await applyAcl({runnerWrite:true});await assert.rejects(provider()(),/PUBLIC_KEY_(RUNNER_WRITE|BROAD_WRITE)_REJECTED/);});
windowsOnly("native reparse junction is detected and rejected",async()=>{await applyAcl();const junction=path.join(root,"junction-"+randomUUID());ps(`New-Item -ItemType Junction -Path '${junction.replaceAll("'","''")}' -Target '${trust.replaceAll("'","''")}' | Out-Null`);const report=await inspector.inspectPath(junction);assert.equal(report.isReparsePoint,true);const linkedKey=path.join(junction,"operator-public.pem");await assert.rejects(provider(inspector,linkedKey)(),/PUBLIC_KEY_(SYMLINK|REPARSE)/);});
windowsOnly("actual fixture alternate, sibling, traversal and UNC paths are rejected",async()=>{await applyAcl();const sibling=path.join(root,"sibling.pem");await writeFile(sibling,publicKey,{encoding:"ascii"});for(const candidate of [sibling,`${trust}\\..\\trust\\operator-public.pem`,"\\\\localhost\\fixture\\operator-public.pem"]){await assert.rejects(provider()(candidate),/PUBLIC_KEY_(ALTERNATE_PATH|TRAVERSAL|UNC_PATH)_REJECTED/);}});
windowsOnly("native file ID distinguishes path replacement and provider fails closed",async()=>{await applyAcl();const before=await inspector.inspectPath(keyPath),replacement=path.join(trust,"replacement.pem");await writeFile(replacement,publicKey,{encoding:"ascii"});ps(aclScript(replacement,false,{}));let replacementBlocked=false,swapped=false;const racing={inspectPath:target=>inspector.inspectPath(target),inspectHandle:async(_handle,target)=>{if(!swapped){try{await rm(keyPath);await rename(replacement,keyPath);swapped=true;}catch{replacementBlocked=true;}}return inspector.inspectPath(target);}};let rejected=false;try{await provider(racing)();}catch(error){rejected=/PUBLIC_KEY_(IDENTITY_CHANGED|PREOPEN_IDENTITY_MISMATCH|PATH_IDENTITY_CHANGED)/.test(String(error));}assert.equal(rejected||replacementBlocked,true);if(swapped){const afterReport=await inspector.inspectPath(keyPath);assert.notEqual(before.fileId,afterReport.fileId);}});
windowsOnly("native inspector missing, crash, timeout and malformed metadata fail closed",async()=>{await assert.rejects(createNativeWindowsAclInspector({helperPath:path.join(root,"missing.exe")}).inspectPath(keyPath),/UNAVAILABLE/);for(const malformed of [{ok:true,available:true},{ok:true,available:true,absolutePath:keyPath,resolvedPath:keyPath,type:"file",owner:"x",ownerSidPresent:true,inheritanceEnabled:false,isReparsePoint:false,volumeSerial:"",fileId:"",size:1,lastWriteFileTime:1,entries:[]}]){const fake=()=>{const listeners={};const stream={on(name,callback){listeners[name]=callback;return stream;}};queueMicrotask(()=>{listeners.data?.(Buffer.from(JSON.stringify(malformed)));listeners.close?.(0);});return{stdout:stream,stderr:{on(){return this;}},on(name,callback){listeners[name]=callback;return this;},kill(){}};};await assert.rejects(createNativeWindowsAclInspector({helperPath,spawnImpl:fake}).inspectPath(keyPath),/MALFORMED/);}const hanging=()=>{const stream={on(){return stream;}};return{stdout:stream,stderr:stream,on(){return this;},kill(){}};};await assert.rejects(createNativeWindowsAclInspector({helperPath,spawnImpl:hanging,timeoutMs:5}).inspectPath(keyPath),/TIMEOUT/);});
windowsOnly("native inspector output and failures do not contain fixture key material",async()=>{await applyAcl();const report=await inspector.inspectPath(keyPath);const serialized=JSON.stringify(report);assert.equal(serialized.includes(publicKey.trim()),false);assert.equal(serialized.includes("PRIVATE KEY"),false);});
