import assert from "node:assert/strict";
import { generateKeyPairSync, createSign } from "node:crypto";
import { EventEmitter } from "node:events";
import { readdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { Classification, ForwardRotationRunnerV2, RunnerState } from "../scripts/runner-v2/state-machine.mjs";
import { OperatorControl } from "../scripts/runner-v2/operator-control.mjs";
import { canonicalActivationManifest, createProductionOperatorAuthorizer, PRODUCTION_IDENTITY } from "../scripts/runner-v2/operator-authorization.mjs";
import { createProductionAdapters, DIRECT_CONFIG, IDENTITY_SQL, POOLER_CONFIG, TARGET_ROLE, VERCEL_TARGET } from "../scripts/runner-v2/production-adapters.mjs";
import { CONNECTION_TIMEOUT_MS, createPgIdentityDriver, createRotationDriver, createSafeProcessExecutor, createVercelCliDriver } from "../scripts/runner-v2/real-drivers.mjs";
import { createTestProductionRuntime } from "../scripts/runner-v2/production-runtime.mjs";
import { operatorPublicKeyFingerprint } from "../scripts/runner-v2/trusted-operator-key.mjs";
import { createPrivilegedClientFactory } from "../scripts/runner-v2/privileged-client-factory.mjs";

const DUMMY=Buffer.from("contract-dummy-secret");
function pgFixture(endpoint, failure={}) { const seen=[];let connects=0;const client={connect:async()=>{connects++;if(failure.connect)throw Object.assign(Error("raw contract-dummy-secret"),failure.connect);},query:async sql=>{seen.push(sql);if(failure.query===sql)throw Object.assign(Error("raw"),failure.error??{});return{rows:[failure.identity??{current_user:TARGET_ROLE,session_user:TARGET_ROLE,current_database:"postgres"}]};},end:async()=>{}};const driver=createPgIdentityDriver({endpoint,clientFactory:config=>(seen.push(config),client)});return{driver,seen,connects:()=>connects};}

test("Direct and Pooler real binding enforce distinct fixed usernames, TLS, timeout, one connection and SQL allowlist",async()=>{for(const endpoint of [DIRECT_CONFIG,POOLER_CONFIG]){const fx=pgFixture(endpoint);await fx.driver.authenticate({...endpoint,password:DUMMY});const session=await fx.driver.open({...endpoint,password:DUMMY});for(const sql of IDENTITY_SQL)await session.execute(sql);await assert.rejects(()=>session.execute("SELECT version();"),{code:"SQL_NOT_ALLOWLISTED"});await session.close();const config=fx.seen[0];assert.equal(config.user,endpoint.username);assert.deepEqual(config.ssl,{rejectUnauthorized:true});assert.equal(config.connectionTimeoutMillis,CONNECTION_TIMEOUT_MS);assert.equal(config.query_timeout,CONNECTION_TIMEOUT_MS);assert.equal(fx.connects(),1);await assert.rejects(()=>fx.driver.authenticate({...endpoint,password:DUMMY}),{code:"DUPLICATE_CONNECTION_ATTEMPT"});}});
test("Direct/Pooler username interchange and endpoint mutation fail closed before connect",async()=>{for(const [endpoint,wrong] of [[DIRECT_CONFIG,POOLER_CONFIG.username],[POOLER_CONFIG,DIRECT_CONFIG.username]]){const fx=pgFixture(endpoint);await assert.rejects(()=>fx.driver.authenticate({...endpoint,username:wrong,password:DUMMY}),{code:"ENDPOINT_IDENTITY_REJECTED"});assert.equal(fx.connects(),0);}});

test("rotation binding fixes role, accepts Buffer, redacts failure and rejects duplicate",async()=>{const queries=[];const driver=createRotationDriver({privilegedClientFactory:()=>({connect:async()=>{},query:async sql=>queries.push(sql),end:async()=>{}})});assert.equal(await driver.rotateRolePassword({role:TARGET_ROLE,password:DUMMY}),true);assert.equal(queries.length,1);assert.match(queries[0],/^ALTER ROLE signalx_entitlements_runtime PASSWORD /);await assert.rejects(()=>driver.rotateRolePassword({role:TARGET_ROLE,password:DUMMY}),{code:"DUPLICATE_ROTATION_ATTEMPT"});const denied=createRotationDriver({privilegedClientFactory:()=>{throw Error("must not call");}});assert.deepEqual(await denied.rotateRolePassword({role:"postgres",password:DUMMY}),{ok:false,classification:Classification.ROTATION_FAILED});});

test("Vercel CLI binding transfers URI only by stdin with fixed safe args and zeroizes it",async()=>{let request,snapshot;const driver=createVercelCliDriver({processExecutor:async value=>{request=value;snapshot=Buffer.from(value.stdin);return{exitCode:0};}});assert.equal(await driver.registerSensitiveFromStdin({target:VERCEL_TARGET,stdin:DUMMY}),true);assert.ok(snapshot.includes(DUMMY));assert.ok(!request.args.some(arg=>arg.includes(DUMMY.toString())||arg.includes("postgresql://")));assert.equal(request.timeoutMs,CONNECTION_TIMEOUT_MS);assert.ok(request.stdin.every(byte=>byte===0));assert.ok(!request.args.includes("DATABASE_URL"));await assert.rejects(()=>driver.registerSensitiveFromStdin({target:VERCEL_TARGET,stdin:DUMMY}),{code:"DUPLICATE_VERCEL_REGISTRATION"});});
test("Vercel target mismatch performs no process operation",async()=>{let count=0;const driver=createVercelCliDriver({processExecutor:async()=>{count++;}});const result=await driver.registerSensitiveFromStdin({target:{...VERCEL_TARGET,project:"wrong"},stdin:DUMMY});assert.equal(result.classification,Classification.VERCEL_PROJECT_MISMATCH);assert.equal(count,0);});
test("safe child-process executor uses shell=false and stdin without secret arguments",async()=>{let options,received,args;const spawnImpl=(file,argv,opts)=>{args=argv;options=opts;const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin={end:value=>{received=Buffer.from(value);queueMicrotask(()=>child.emit("close",0));}};child.kill=()=>{};return child;};const execute=createSafeProcessExecutor({spawnImpl});const result=await execute({file:"vercel",args:["env","add","SAFE_NAME"],stdin:DUMMY,timeoutMs:100});assert.equal(result.exitCode,0);assert.deepEqual(received,DUMMY);assert.equal(options.shell,false);assert.equal(options.windowsHide,true);assert.ok(!args.some(value=>value.includes(DUMMY.toString())));});
for(const safeCode of ["VERCEL_AUTH_FAILED","VERCEL_PROJECT_MISMATCH","VERCEL_ENV_ALREADY_EXISTS","VERCEL_REGISTRATION_FAILED"])test(`${safeCode} remains a safe Vercel classification`,async()=>{const driver=createVercelCliDriver({processExecutor:async()=>({exitCode:1,safeCode})});const result=await driver.registerSensitiveFromStdin({target:VERCEL_TARGET,stdin:DUMMY});assert.equal(result.classification,Classification[safeCode]);});
test("Vercel metadata verification checks fixed name, environment, type and project ID",async()=>{const metadata={name:VERCEL_TARGET.variable,environment:VERCEL_TARGET.environment,type:"Sensitive",projectId:VERCEL_TARGET.projectId};const driver=createVercelCliDriver({processExecutor:async()=>({exitCode:0,stdout:Buffer.from(JSON.stringify(metadata)),stderr:Buffer.alloc(0)})});assert.equal(await driver.verifyMetadata({target:VERCEL_TARGET}),true);metadata.projectId="wrong";const mismatch=createVercelCliDriver({processExecutor:async()=>({exitCode:0,stdout:Buffer.from(JSON.stringify(metadata)),stderr:Buffer.alloc(0)})});assert.equal(await mismatch.verifyMetadata({target:VERCEL_TARGET}),false);});

function normalizationFixture(kind,error,identity,rollback=false){const driver={authenticate:async()=>{if(error)throw error;},open:async()=>({execute:async sql=>{if(rollback&&sql===IDENTITY_SQL[2])throw error??Error("rollback");if(sql===IDENTITY_SQL[1])return identity??{currentUser:TARGET_ROLE,sessionUser:TARGET_ROLE,currentDatabase:"postgres"};},close:async()=>{}})};const noop={authenticate:async()=>{},open:async()=>({execute:async sql=>sql===IDENTITY_SQL[1]?{currentUser:TARGET_ROLE,sessionUser:TARGET_ROLE,currentDatabase:"postgres"}:undefined,close:async()=>{}})};return createProductionAdapters({rotationDriver:{rotateRolePassword:async()=>true},directDriver:kind==="DIRECT"?driver:noop,poolerDriver:kind==="POOLER"?driver:noop,vercelDriver:{registerSensitiveFromStdin:async()=>true,verifyMetadata:async()=>true}});}
for(const [label,error,suffix] of [["auth",Object.assign(Error(),{code:"28P01"}),"AUTH_FAILED"],["timeout",Object.assign(Error(),{code:"ETIMEDOUT"}),"TIMEOUT"],["TLS",Object.assign(Error(),{code:"CERT_HAS_EXPIRED"}),"TLS_FAILED"],["network",Object.assign(Error(),{code:"ECONNREFUSED"}),"NETWORK_FAILED"],["unknown",Error("raw password=contract-dummy-secret"),"UNKNOWN_SAFE_FAILURE"]])for(const kind of ["DIRECT","POOLER"])test(`${kind} ${label} error normalization`,async()=>{const adapters=normalizationFixture(kind,error);const result=await adapters[`${kind.toLowerCase()}Auth`](DUMMY);assert.equal(result.classification,suffix==="UNKNOWN_SAFE_FAILURE"?Classification.UNKNOWN_SAFE_FAILURE:Classification[`${kind}_${suffix}`]);assert.ok(!JSON.stringify(result).includes(DUMMY.toString()));});
for(const kind of ["DIRECT","POOLER"])test(`${kind} identity mismatch and rollback normalization`,async()=>{let adapters=normalizationFixture(kind,null,{currentUser:"wrong",sessionUser:TARGET_ROLE,currentDatabase:"postgres"});let result=await adapters[`${kind.toLowerCase()}Identity`](DUMMY);assert.equal(result.classification,Classification[`${kind}_IDENTITY_MISMATCH`]);adapters=normalizationFixture(kind,Error("raw"),undefined,true);result=await adapters[`${kind.toLowerCase()}Identity`](DUMMY);assert.equal(result.classification,Classification[`${kind}_ROLLBACK_FAILED`]);});

function signedAuthorization(overrides={}){const {publicKey,privateKey}=generateKeyPairSync("rsa",{modulusLength:3072});const pem=publicKey.export({type:"spki",format:"pem"});const now=1_800_000_000_000;const manifest={command:"ACTIVATE",...PRODUCTION_IDENTITY,currentState:RunnerState.PREFLIGHT,nonce:"contract-nonce-0001",expiresAt:now+60_000,...overrides};const signer=createSign("SHA256");signer.update(canonicalActivationManifest(manifest));signer.end();return{authorize:createProductionOperatorAuthorizer({trustedPublicKey:pem,approvedFingerprint:operatorPublicKeyFingerprint(pem),now:()=>now}),authorization:{manifest,signature:signer.sign(privateKey)}};}
test("signed Production activation authorizes once and rejects replay",async()=>{const signed=signedAuthorization();assert.equal(await signed.authorize({command:"ACTIVATE",authorization:signed.authorization,currentState:RunnerState.PREFLIGHT}),true);assert.equal(await signed.authorize({command:"ACTIVATE",authorization:signed.authorization,currentState:RunnerState.PREFLIGHT}),false);});
for(const [label,overrides] of [["wrong Production project",{productionProject:"wrong"}],["wrong Vercel project",{vercelProject:"wrong"}],["wrong environment",{environment:"preview"}],["wrong role",{role:"postgres"}]])test(`${label} rejects activation`,async()=>{const signed=signedAuthorization(overrides);assert.equal(await signed.authorize({command:"ACTIVATE",authorization:signed.authorization,currentState:RunnerState.PREFLIGHT}),false);});
test("invalid signature and boolean authorization reject activation",async()=>{const signed=signedAuthorization();signed.authorization.signature[0]^=1;assert.equal(await signed.authorize({command:"ACTIVATE",authorization:signed.authorization,currentState:RunnerState.PREFLIGHT}),false);assert.equal(await signed.authorize({command:"ACTIVATE",authorization:true,currentState:RunnerState.PREFLIGHT}),false);});
test("Production runtime construction is inert and exposes only the authorized facade",()=>{const {publicKey}=generateKeyPairSync("rsa",{modulusLength:3072}),pem=publicKey.export({type:"spki",format:"pem"});let clients=0,processes=0,credentialReads=0;class FakeClient{constructor(){clients++;}}const runtime=createTestProductionRuntime({trustedOperatorPublicKey:pem,approvedOperatorKeyFingerprint:operatorPublicKeyFingerprint(pem),privilegedCredentialProvider:async()=>{credentialReads++;},preflight:async()=>true,ClientClass:FakeClient,PrivilegedClientClass:FakeClient,processExecutor:async()=>{processes++;}});assert.deepEqual(Object.keys(runtime),["command","status","events"]);assert.equal(runtime.runner,undefined);assert.equal(runtime.control,undefined);for(const primitive of ["preflight","rotate","directAuth","completeVercelRecovery"])assert.equal(runtime[primitive],undefined);assert.equal(runtime.status.state,RunnerState.PREFLIGHT);assert.equal(clients,0);assert.equal(processes,0);assert.equal(credentialReads,0);});

function activationFacade(overrides={},wrongSigner=false){const pair=generateKeyPairSync("rsa",{modulusLength:3072}),other=generateKeyPairSync("rsa",{modulusLength:3072}),pem=pair.publicKey.export({type:"spki",format:"pem"}),manifest={command:"ACTIVATE",...PRODUCTION_IDENTITY,currentState:RunnerState.PREFLIGHT,nonce:"public-boundary-nonce-0001",expiresAt:Date.now()+60_000,...overrides},signer=createSign("SHA256");signer.update(canonicalActivationManifest(manifest));signer.end();const runtime=createTestProductionRuntime({trustedOperatorPublicKey:pem,approvedOperatorKeyFingerprint:operatorPublicKeyFingerprint(pem),privilegedCredentialProvider:async()=>{throw Error("unused");},preflight:async()=>true,ClientClass:class{},PrivilegedClientClass:class{},processExecutor:async()=>{throw Error("unused");}});return{runtime,authorization:{manifest,signature:signer.sign(wrongSigner?other.privateKey:pair.privateKey)}};}
test("public Production facade rejects unsigned and malformed ACTIVATE",async()=>{for(const authorization of [undefined,{},true,{manifest:{command:"ACTIVATE"},signature:Buffer.alloc(1)}]){const {runtime}=activationFacade();await assert.rejects(()=>runtime.command("ACTIVATE",authorization),{code:"OPERATOR_NOT_AUTHORIZED"});assert.equal(runtime.status.state,RunnerState.PREFLIGHT);}});
test("public Production facade rejects wrong signer, expiry, and wrong identity bindings",async()=>{for(const [overrides,wrongSigner] of [[{},true],[{expiresAt:Date.now()-1},false],[{productionProject:"wrong"},false],[{role:"postgres"},false],[{targetVariable:"DATABASE_URL"},false]]){const {runtime,authorization}=activationFacade(overrides,wrongSigner);await assert.rejects(()=>runtime.command("ACTIVATE",authorization),{code:"OPERATOR_NOT_AUTHORIZED"});assert.equal(runtime.status.state,RunnerState.PREFLIGHT);}});
test("public Production facade accepts signed ACTIVATE once and replay cannot change state",async()=>{const {runtime,authorization}=activationFacade();assert.equal(await runtime.command("ACTIVATE",authorization),true);assert.equal(runtime.status.state,RunnerState.READY_FOR_ACTIVATION);await assert.rejects(()=>runtime.command("ACTIVATE",authorization));assert.equal(runtime.status.state,RunnerState.READY_FOR_ACTIVATION);});

test("raw output is captured, secret absent from stdout/stderr/temp, DATABASE_URL untouched",async()=>{const dir=await mkdtemp(join(tmpdir(),"runner-contract-")),before=await readdir(dir),out=[],err=[],oldOut=process.stdout.write,oldErr=process.stderr.write,oldUrl=process.env.DATABASE_URL;process.stdout.write=x=>(out.push(String(x)),true);process.stderr.write=x=>(err.push(String(x)),true);try{const driver=createVercelCliDriver({processExecutor:async()=>({exitCode:1,stdout:DUMMY.toString(),stderr:DUMMY.toString()})});const result=await driver.registerSensitiveFromStdin({target:VERCEL_TARGET,stdin:DUMMY});assert.equal(result.classification,Classification.VERCEL_REGISTRATION_FAILED);}finally{process.stdout.write=oldOut;process.stderr.write=oldErr;}assert.deepEqual(await readdir(dir),before);assert.equal(process.env.DATABASE_URL,oldUrl);assert.ok(!out.join("").includes(DUMMY)&&!err.join("").includes(DUMMY));await rm(dir,{recursive:true,force:true});});

test("real bindings integrate with runner and preserve downstream attempt guards",async()=>{for(const fail of ["direct","pooler"]){const calls=[];const good={authenticate:async()=>{},open:async()=>({execute:async sql=>sql===IDENTITY_SQL[1]?{currentUser:TARGET_ROLE,sessionUser:TARGET_ROLE,currentDatabase:"postgres"}:undefined,close:async()=>{}})};const bad={...good,authenticate:async()=>{throw Object.assign(Error("safe"),{code:"28P01"});}};const adapters=createProductionAdapters({rotationDriver:{rotateRolePassword:async()=>true},directDriver:fail==="direct"?bad:good,poolerDriver:fail==="pooler"?bad:good,vercelDriver:{registerSensitiveFromStdin:async()=>{calls.push("vercel");return true;},verifyMetadata:async()=>true}});const runner=new ForwardRotationRunnerV2({adapters});const control=new OperatorControl({runner,secretFactory:()=>Buffer.from(DUMMY),authorize:async()=>true});for(const command of ["ACTIVATE","ROTATE","DIRECT_AUTH","DIRECT_IDENTITY_CHECK","POOLER_AUTH"]){const result=await control.command(command);if(result===false)break;}if(fail==="direct"){assert.equal(runner.status.attempts.pooler,0);assert.equal(runner.status.attempts.vercel,0);}else assert.equal(runner.status.attempts.vercel,0);assert.equal(calls.length,0);await runner.cleanup();}});
