import test,{before,after} from "node:test";
import assert from "node:assert/strict";
import {execFileSync,spawn} from "node:child_process";
import {createHash,generateKeyPairSync} from "node:crypto";
import {mkdtemp,mkdir,writeFile,readFile,rm,copyFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createNativeWindowsAclInspector} from "../scripts/runner-v2/native-windows-acl-inspector.mjs";
import {createTestTrustedWindowsKeyReadProvider,loadTrustedKeyReadBinding,resolveProductionKeyReaderPath} from "../scripts/runner-v2/trusted-windows-key-reader.mjs";
import {operatorPublicKeyFingerprint} from "../scripts/runner-v2/trusted-operator-key.mjs";

const windowsOnly=process.platform==="win32"?test:test.skip,csc="C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\csc.exe";
const elevatedOwnerOnly=process.platform==="win32"&&process.env.SIGNALX_ELEVATED_OWNER_ACCEPTANCE==="1"?test:test.skip;
let root,trust,keyPath,readerPath,inspectorPath,inspector,publicKey,runnerSid="S-1-5-32-545",provisionerSid,readerHash;
function ps(script){return execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-EncodedCommand",Buffer.from(script,"utf16le").toString("base64")],{windowsHide:true,timeout:15000,stdio:["ignore","pipe","pipe"]});}
function psElevated(script){const encoded=Buffer.from(script,"utf16le").toString("base64"),launcher=`$p=Start-Process -FilePath 'powershell.exe' -Verb RunAs -Wait -PassThru -ArgumentList @('-NoProfile','-NonInteractive','-EncodedCommand','${encoded}');exit $p.ExitCode`;return execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",launcher],{windowsHide:false,timeout:60000,stdio:["ignore","pipe","pipe"]});}
function aclScript(target,isDirectory,{inheritance=false,broadWrite=false,runnerWrite=false}={}){const p=target.replaceAll("'","''");return `$p='${p}';$d=$${isDirectory?"true":"false"};$s=if($d){New-Object Security.AccessControl.DirectorySecurity}else{New-Object Security.AccessControl.FileSecurity};$s.SetAccessRuleProtection($${inheritance?"false":"true"},$false);$me=[Security.Principal.WindowsIdentity]::GetCurrent().User;$s.SetOwner($me);$i=if($d){[Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit}else{[Security.AccessControl.InheritanceFlags]::None};$n=[Security.AccessControl.PropagationFlags]::None;$a=[Security.AccessControl.AccessControlType]::Allow;$u=New-Object Security.Principal.SecurityIdentifier('S-1-5-32-545');$sys=New-Object Security.Principal.SecurityIdentifier('S-1-5-18');$r=[Security.AccessControl.FileSystemRights]::ReadAndExecute -bor [Security.AccessControl.FileSystemRights]::ReadPermissions;$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($u,$r,$i,$n,$a)));$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($sys,[Security.AccessControl.FileSystemRights]::FullControl,$i,$n,$a)));$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($me,[Security.AccessControl.FileSystemRights]::FullControl,$i,$n,$a)));${broadWrite?"$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule((New-Object Security.Principal.SecurityIdentifier('S-1-5-11')),[Security.AccessControl.FileSystemRights]::Write,$i,$n,$a)));":""}${runnerWrite?"$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($u,[Security.AccessControl.FileSystemRights]::Delete,$i,$n,$a)));":""}if($d){(New-Object IO.DirectoryInfo($p)).SetAccessControl($s)}else{(New-Object IO.FileInfo($p)).SetAccessControl($s)}`;}
async function setKeyAcl(options={}){ps(aclScript(trust,true,options));ps(aclScript(keyPath,false,options));}
async function setReaderAcl(options={}){ps(aclScript(readerPath,false,options));}
async function sha(file){return`sha256:${createHash("sha256").update(await readFile(file)).digest("hex")}`;}
function reader(overrides={}){return createTestTrustedWindowsKeyReadProvider({helperPath:readerPath,keyPath,trustRoot:trust,runnerSid,provisionerSid,expectedHelperHash:readerHash,helperInspector:inspector,...overrides});}
before(async()=>{if(process.platform!=="win32")return;root=await mkdtemp(path.join(os.tmpdir(),"signalx-trusted-reader-fixture-"));trust=path.join(root,"trust");await mkdir(trust);keyPath=path.join(trust,"operator-public.pem");readerPath=path.join(root,"native-windows-key-reader.exe");inspectorPath=path.join(root,"native-acl-inspector.exe");execFileSync(csc,["/nologo","/target:exe","/platform:x64",`/out:${readerPath}`,path.resolve("scripts/runner-v2/trusted-windows-key-reader-helper.cs")],{windowsHide:true,timeout:30000});execFileSync(csc,["/nologo","/target:exe","/platform:x64",`/out:${inspectorPath}`,path.resolve("scripts/runner-v2/native-windows-acl-inspector-helper.cs")],{windowsHide:true,timeout:30000});await new Promise(resolve=>setTimeout(resolve,1000));publicKey=generateKeyPairSync("rsa",{modulusLength:3072,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}}).publicKey;await writeFile(keyPath,publicKey,"ascii");await setKeyAcl();await setReaderAcl();inspector=createNativeWindowsAclInspector({helperPath:inspectorPath});provisionerSid=(await inspector.inspectPath(readerPath)).owner;readerHash=await sha(readerPath);});
after(async()=>{if(root&&path.resolve(root).startsWith(path.resolve(os.tmpdir()))&&path.basename(root).startsWith("signalx-trusted-reader-fixture-"))await rm(root,{recursive:true,force:true,maxRetries:3,retryDelay:50});});

windowsOnly("Production helper path uses OS CommonApplicationData and ignores ProgramData environment override",()=>{const original=process.env.ProgramData;try{process.env.ProgramData="C:\\attacker-controlled";const actual=resolveProductionKeyReaderPath(),known=ps("[Environment]::GetFolderPath([Environment+SpecialFolder]::CommonApplicationData)").toString("utf8").trim();assert.equal(actual,path.win32.join(known,"SignalX","runner-v2","bin","native-windows-key-reader.exe"));assert.equal(actual.includes("attacker-controlled"),false);}finally{if(original===undefined)delete process.env.ProgramData;else process.env.ProgramData=original;}});

for(const right of ["WriteData","AppendData","WriteExtendedAttributes","WriteAttributes","Delete","ChangePermissions","TakeOwnership","Modify","FullControl"])windowsOnly(`native ACL decision rejects runner ${right} only`,()=>{const result=spawn(readerPath,["acl-rights-fixture","runner",right],{windowsHide:true});return new Promise((resolve,reject)=>result.on("error",reject).on("close",code=>{try{assert.equal(code,31);resolve();}catch(error){reject(error);}}));});
windowsOnly("native ACL decision rejects broad principal single WriteData",()=>{const result=spawn(readerPath,["acl-rights-fixture","broad","WriteData"],{windowsHide:true});return new Promise((resolve,reject)=>result.on("error",reject).on("close",code=>{try{assert.equal(code,31);resolve();}catch(error){reject(error);}}));});
windowsOnly("native ACL decision accepts runner read-execute only",()=>{const result=spawn(readerPath,["acl-rights-fixture","runner","ReadAndExecute"],{windowsHide:true});return new Promise((resolve,reject)=>result.on("error",reject).on("close",code=>{try{assert.equal(code,0);resolve();}catch(error){reject(error);}}));});

windowsOnly("trusted helper validates and reads key through one handle",async()=>{await setKeyAcl();await setReaderAcl();const result=await reader()();assert.equal(result.metadata.sameHandle,true);assert.equal(result.key.toString("ascii"),publicKey);result.key.fill(0);});
windowsOnly("helper rejects inheritance, broad write, and runner write",async()=>{for(const options of [{inheritance:true},{broadWrite:true},{runnerWrite:true}]){await setKeyAcl(options);await assert.rejects(reader()(),/KEY_READER_FAILED/);}});
windowsOnly("helper rejects oversized and malformed keys; Node rejects RSA2048",async()=>{await setKeyAcl();await writeFile(keyPath,Buffer.alloc(16*1024+1,65));await setKeyAcl();await assert.rejects(reader()(),/KEY_READER_FAILED/);await writeFile(keyPath,"not pem","ascii");await setKeyAcl();const malformed=await reader()();await assert.rejects(loadTrustedKeyReadBinding({keyReadProvider:async()=>malformed,approvedFingerprintProvider:async()=>"sha256:"+"0".repeat(64)}));const weak=generateKeyPairSync("rsa",{modulusLength:2048,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}}).publicKey;await writeFile(keyPath,weak,"ascii");await setKeyAcl();const weakResult=await reader()();await assert.rejects(loadTrustedKeyReadBinding({keyReadProvider:async()=>weakResult,approvedFingerprintProvider:async()=>"sha256:"+"0".repeat(64)}));});
windowsOnly("RSA3072 and exact separate fingerprint bind successfully",async()=>{await writeFile(keyPath,publicKey,"ascii");await setKeyAcl();const binding=await loadTrustedKeyReadBinding({keyReadProvider:reader(),approvedFingerprintProvider:async()=>operatorPublicKeyFingerprint(publicKey)});assert.equal(binding.approvedOperatorKeyFingerprint,operatorPublicKeyFingerprint(publicKey));});
windowsOnly("fingerprint mismatch rejects and key buffer is zeroized",async()=>{await setKeyAcl();const result=await reader()();await assert.rejects(loadTrustedKeyReadBinding({keyReadProvider:async()=>result,approvedFingerprintProvider:async()=>"sha256:"+"0".repeat(64)}));assert.ok(result.key.every(byte=>byte===0));});
windowsOnly("helper hash mismatch and unacceptable helper ACL reject before execution",async()=>{await setReaderAcl();await assert.rejects(reader({expectedHelperHash:"sha256:"+"0".repeat(64)})(),/HELPER_HASH_MISMATCH/);await setReaderAcl({runnerWrite:true});await assert.rejects(reader()(),/HELPER_ACL_REJECTED|HELPER_RUNNER_ACL_REJECTED/);});
windowsOnly("helper reparse and missing helper fail closed",async()=>{await setReaderAcl();const junction=path.join(root,"bin-junction");const bin=path.join(root,"bin");await mkdir(bin);const copy=path.join(bin,"native-windows-key-reader.exe");await writeFile(copy,await readFile(readerPath));ps(aclScript(copy,false,{}));ps(`New-Item -ItemType Junction -Path '${junction}' -Target '${bin}'|Out-Null`);const linked=path.join(junction,"native-windows-key-reader.exe");await assert.rejects(reader({helperPath:linked,expectedHelperHash:await sha(copy)})(),/HELPER_(ACL|IDENTITY|REPARSE)_REJECTED/);await assert.rejects(reader({helperPath:path.join(root,"missing.exe")})());});
windowsOnly("helper binary replacement between hash and launch fails closed",async()=>{await setReaderAcl();const backup=path.join(root,"reader-backup.exe");await copyFile(readerPath,backup);let replaced=false;const replacingSpawn=(file,args,options)=>{if(!replaced){execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",`Copy-Item -LiteralPath '${inspectorPath}' -Destination '${readerPath}' -Force`],{windowsHide:true});ps(aclScript(readerPath,false,{}));replaced=true;}return spawn(file,args,options);};try{await assert.rejects(reader({spawnImpl:replacingSpawn})(),/KEY_READER_(FAILED|UNAVAILABLE)|HELPER_REPLACED/);}finally{await copyFile(backup,readerPath);await setReaderAcl();}assert.equal(replaced,true);});
windowsOnly("malformed framed protocol and raw helper failure fail closed without key forwarding",async()=>{await setReaderAcl();const fake=()=>{const handlers={},stream={on(name,cb){handlers[name]=cb;return stream;}};queueMicrotask(()=>{handlers.data?.(Buffer.from("not-a-frame"));handlers.close?.(0);});return{stdout:stream,stderr:{on(){return this;}},on(name,cb){handlers[name]=cb;return this;},kill(){}};};await assert.rejects(reader({spawnImpl:fake})(),/PROTOCOL/);});
elevatedOwnerOnly("elevated actual unapproved owner SID is natively observed and rejected",async()=>{await writeFile(keyPath,publicKey,"ascii");await setKeyAcl();await setReaderAcl();const baseline=await reader()();baseline.key.fill(0);const before=await inspector.inspectPath(keyPath);assert.equal(before.owner,provisionerSid);const escaped=keyPath.replaceAll("'","''");psElevated(`$p='${escaped}';$s=(New-Object IO.FileInfo($p)).GetAccessControl([Security.AccessControl.AccessControlSections]::Owner -bor [Security.AccessControl.AccessControlSections]::Access);$s.SetOwner((New-Object Security.Principal.SecurityIdentifier('S-1-5-32-544')));(New-Object IO.FileInfo($p)).SetAccessControl($s)`);const changed=await inspector.inspectPath(keyPath);assert.equal(changed.owner,"S-1-5-32-544");try{await assert.rejects(reader()(),/KEY_READER_OWNER_REJECTED/);}finally{psElevated(`$p='${escaped}';$s=(New-Object IO.FileInfo($p)).GetAccessControl([Security.AccessControl.AccessControlSections]::Owner -bor [Security.AccessControl.AccessControlSections]::Access);$s.SetOwner((New-Object Security.Principal.SecurityIdentifier('${provisionerSid}')));(New-Object IO.FileInfo($p)).SetAccessControl($s)`);await setKeyAcl();}});
test.skip("approved SYSTEM owner requires a separately privileged fixture token",()=>{});
