import assert from "node:assert/strict";
import { createSign, generateKeyPairSync } from "node:crypto";
import test from "node:test";
import { ForwardRotationRunnerV2, RunnerState, VercelRecoveryObservation } from "../scripts/runner-v2/state-machine.mjs";
import { OperatorControl } from "../scripts/runner-v2/operator-control.mjs";
import { PRODUCTION_IDENTITY } from "../scripts/runner-v2/operator-authorization.mjs";
import { canonicalRecoveryManifest, createRecoveryAuthorizer, RecoveryAction } from "../scripts/runner-v2/recovery-authorization.mjs";
import { operatorPublicKeyFingerprint } from "../scripts/runner-v2/trusted-operator-key.mjs";

const SECRET_TEXT="recovery-fixture-secret";
function fixture({registrationFails=true,metadataFails=false,maxRecoveryHoldMs}={}){let owned,writes=0;const adapters={preflight:async()=>true,rotate:async()=>true,directAuth:async()=>({ok:true}),directIdentity:async()=>({ok:true,rollback:true}),poolerAuth:async()=>({ok:true}),poolerIdentity:async()=>({ok:true,rollback:true}),vercelRegister:async()=>{writes++;return registrationFails?{ok:false,classification:"UNKNOWN_SAFE_FAILURE"}:true;},verifyEnvMetadata:async()=>!metadataFails,cleanup:async()=>{}};const runner=new ForwardRotationRunnerV2({adapters,runId:"run-recovery-fixture-001",maxRecoveryHoldMs});const pair=generateKeyPairSync("rsa",{modulusLength:3072}),pem=pair.publicKey.export({type:"spki",format:"pem"}),fingerprint=operatorPublicKeyFingerprint(pem),recoveryAuthorize=createRecoveryAuthorizer({trustedPublicKey:pem,approvedFingerprint:fingerprint,now:()=>2_100_000_000_000});const control=new OperatorControl({runner,authorize:async()=>true,recoveryAuthorize,secretFactory:()=>{owned=Buffer.from(SECRET_TEXT);return owned;}});return{runner,control,privateKey:pair.privateKey,owned:()=>owned,writes:()=>writes,now:2_100_000_000_000};}
async function reachFailure(fx,{metadata=false}={}){for(const command of ["ACTIVATE","ROTATE","DIRECT_AUTH","DIRECT_IDENTITY_CHECK","POOLER_AUTH","POOLER_IDENTITY_CHECK"])assert.equal(await fx.control.command(command),true);assert.equal(await fx.control.command("VERCEL_REGISTER"),metadata?true:false);if(metadata)assert.equal(await fx.control.command("VERIFY_ENV_METADATA"),false);}
function recoveryAuthorization(fx,overrides={}){const status=fx.runner.status,manifest={command:"RECOVER_VERCEL",recoveryAction:RecoveryAction.ACCEPT_PRESENT_AND_CLEANUP,...PRODUCTION_IDENTITY,currentHoldState:RunnerState.HOLD,originalRunId:status.runId,originalRegistrationAttemptId:status.registrationAttemptId,operatorObservation:VercelRecoveryObservation.PRESENT_EXPECTED_METADATA,nonce:"recovery-nonce-0001",expiresAt:fx.now+60_000,...overrides};const signer=createSign("SHA256");signer.update(canonicalRecoveryManifest(manifest));signer.end();return{manifest,signature:signer.sign(fx.privateKey)};}
async function observe(fx,value){return fx.control.command("VERCEL_RECOVERY_OBSERVE",{observation:value});}

test("uncertain registration enters HOLD, retains secret, and cannot retry",async()=>{const fx=fixture();await reachFailure(fx);assert.equal(fx.runner.status.state,RunnerState.HOLD);assert.equal(fx.runner.status.credentialHeld,true);assert.equal(fx.runner.status.attempts.vercel,1);await assert.rejects(()=>fx.runner.vercelRegister(),{code:"INVALID_STATE"});assert.equal(fx.writes(),1);await fx.control.command("ABORT");});
test("recovery HOLD rejects direct cleanup without signed completion",async()=>{const fx=fixture();await reachFailure(fx);await assert.rejects(()=>fx.runner.cleanup(),{code:"RECOVERY_HOLD_REQUIRES_SIGNED_COMPLETION_OR_ABORT"});assert.equal(fx.runner.status.credentialHeld,true);await fx.control.command("ABORT");});
test("PRESENT plus valid signed recovery cleans up to DONE without another write",async()=>{const fx=fixture();await reachFailure(fx);await observe(fx,VercelRecoveryObservation.PRESENT_EXPECTED_METADATA);assert.equal(await fx.control.command("RECOVER_VERCEL_PRESENT",recoveryAuthorization(fx)),undefined);assert.equal(fx.runner.status.state,RunnerState.DONE);assert.equal(fx.writes(),1);assert.ok(fx.owned().every(byte=>byte===0));});
test("PRESENT without authorization is rejected",async()=>{const fx=fixture();await reachFailure(fx);await observe(fx,VercelRecoveryObservation.PRESENT_EXPECTED_METADATA);await assert.rejects(()=>fx.control.command("RECOVER_VERCEL_PRESENT",{}),{code:"RECOVERY_NOT_AUTHORIZED"});await fx.control.command("ABORT");});
test("recovery authorization from the wrong fixture signer is rejected",async()=>{const fx=fixture();await reachFailure(fx);await observe(fx,VercelRecoveryObservation.PRESENT_EXPECTED_METADATA);const authorization=recoveryAuthorization(fx),other=generateKeyPairSync("rsa",{modulusLength:3072}),signer=createSign("SHA256");signer.update(canonicalRecoveryManifest(authorization.manifest));signer.end();authorization.signature=signer.sign(other.privateKey);await assert.rejects(()=>fx.control.command("RECOVER_VERCEL_PRESENT",authorization),{code:"RECOVERY_NOT_AUTHORIZED"});await fx.control.command("ABORT");});
for(const [name,overrides] of [["different run",{originalRunId:"other-run"}],["different attempt",{originalRegistrationAttemptId:"other-attempt"}],["wrong target",{targetVariable:"DATABASE_URL"}],["wrong project",{vercelProjectId:"wrong"}],["expired",{expiresAt:2_099_999_999_999}]])test(`${name} recovery authorization is rejected`,async()=>{const fx=fixture();await reachFailure(fx);await observe(fx,VercelRecoveryObservation.PRESENT_EXPECTED_METADATA);await assert.rejects(()=>fx.control.command("RECOVER_VERCEL_PRESENT",recoveryAuthorization(fx,overrides)),{code:"RECOVERY_NOT_AUTHORIZED"});await fx.control.command("ABORT");});
for(const observation of [VercelRecoveryObservation.ABSENT,VercelRecoveryObservation.MISMATCH,VercelRecoveryObservation.UNKNOWN])test(`${observation} remains HOLD and cannot complete or retry`,async()=>{const fx=fixture();await reachFailure(fx);await observe(fx,observation);assert.equal(fx.runner.status.state,RunnerState.HOLD);await assert.rejects(()=>fx.control.command("RECOVER_VERCEL_PRESENT",recoveryAuthorization(fx)),{code:"RECOVERY_NOT_AUTHORIZED"});await assert.rejects(()=>fx.runner.vercelRegister(),{code:"INVALID_STATE"});assert.equal(fx.writes(),1);await fx.control.command("ABORT");});
test("metadata verification failure uses recovery without re-registration",async()=>{const fx=fixture({registrationFails:false,metadataFails:true});await reachFailure(fx,{metadata:true});assert.equal(fx.runner.status.recoveryKind,"METADATA_VERIFICATION_FAILED");await observe(fx,VercelRecoveryObservation.PRESENT_EXPECTED_METADATA);await fx.control.command("RECOVER_VERCEL_PRESENT",recoveryAuthorization(fx));assert.equal(fx.runner.status.state,RunnerState.DONE);assert.equal(fx.writes(),1);});
test("recovery nonce replay is rejected",async()=>{const fx=fixture();await reachFailure(fx);await observe(fx,VercelRecoveryObservation.PRESENT_EXPECTED_METADATA);const auth=recoveryAuthorization(fx);await fx.control.command("RECOVER_VERCEL_PRESENT",auth);await assert.rejects(()=>fx.control.command("RECOVER_VERCEL_PRESENT",auth),{code:"RECOVERY_NOT_AUTHORIZED"});});
test("ABORT is terminal, distinct from DONE, zeroizes secret, and records provisioning risk",async()=>{const fx=fixture();await reachFailure(fx);await fx.control.command("ABORT");assert.equal(fx.runner.status.state,RunnerState.ABORTED);assert.equal(fx.runner.status.credentialHeld,false);assert.equal(fx.runner.status.terminalClassification,"ABORTED_ROTATED_CREDENTIAL_MAY_BE_UNPROVISIONED");assert.ok(fx.owned().every(byte=>byte===0));assert.equal(fx.writes(),1);});
test("HOLD expiry automatically zeroizes and ABORTS without writes",async()=>{const fx=fixture({maxRecoveryHoldMs:5});await reachFailure(fx);await new Promise(resolve=>setTimeout(resolve,20));assert.equal(fx.runner.status.state,RunnerState.ABORTED);assert.ok(fx.owned().every(byte=>byte===0));assert.equal(fx.writes(),1);});
test("recovery events and output contain no secret, DATABASE_URL is untouched, deploy driver is absent",async()=>{const before=process.env.DATABASE_URL,out=[],err=[],oldOut=process.stdout.write,oldErr=process.stderr.write;process.stdout.write=x=>(out.push(String(x)),true);process.stderr.write=x=>(err.push(String(x)),true);try{const fx=fixture();await reachFailure(fx);assert.ok(!JSON.stringify(fx.runner.events).includes(SECRET_TEXT));assert.equal("deploy" in fx.runner,false);await fx.control.command("ABORT");}finally{process.stdout.write=oldOut;process.stderr.write=oldErr;}assert.equal(process.env.DATABASE_URL,before);assert.ok(!out.join("").includes(SECRET_TEXT)&&!err.join("").includes(SECRET_TEXT));});
