import assert from "node:assert/strict";
import { generateKeyPairSync } from "node:crypto";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { operatorPublicKeyFingerprint } from "../scripts/runner-v2/trusted-operator-key.mjs";
import { createProductionTrustedOperatorPublicKeyProvider, createTestTrustedOperatorPublicKeyProvider, loadTestTrustedOperatorBinding, MAX_PUBLIC_KEY_BYTES } from "../scripts/runner-v2/windows-trusted-key-provider.mjs";

const RUNNER="TEST\\RUNNER",ADMIN="BUILTIN\\ADMINISTRATORS",SYSTEM="NT AUTHORITY\\SYSTEM";
function acl({directory=false,available=true,reparse=false,fileId="file-1",owner=ADMIN,inheritanceEnabled=false,entries}={}){return{available,isReparsePoint:reparse,fileId,volumeSerial:"volume-1",owner,inheritanceEnabled,entries:entries??[{principal:RUNNER,permissions:directory?["TRAVERSE","READ_ATTRIBUTES","READ_PERMISSIONS"]:["READ","READ_ATTRIBUTES","READ_PERMISSIONS"]},{principal:SYSTEM,permissions:["FULL_CONTROL"]},{principal:ADMIN,permissions:["FULL_CONTROL"]}]};}
function inspector(root,overrides={}){return{inspectPath:async value=>{const key=path.win32.normalize(value).toLowerCase();if(overrides[key])return overrides[key];return acl({directory:key===path.win32.normalize(root).toLowerCase(),fileId:key===path.win32.normalize(root).toLowerCase()?"root-1":"file-1"});},inspectHandle:async()=>overrides.handle??acl()};}
function key(type="rsa",modulusLength=3072,format="spki"){const pair=type==="rsa"?generateKeyPairSync("rsa",{modulusLength}):generateKeyPairSync("ec",{namedCurve:"P-256"});return pair.publicKey.export({type:format,format:"pem"});}
async function fixture(content=key()){const root=await mkdtemp(path.join(tmpdir(),"runner-key-provider-")),file=path.join(root,"operator-public.pem");await writeFile(file,content);const aclInspector=inspector(root);const provider=createTestTrustedOperatorPublicKeyProvider({expectedPath:file,approvedRoot:root,aclInspector,runnerPrincipal:RUNNER,provisionerPrincipals:[ADMIN]});return{root,file,provider,aclInspector,cleanup:()=>rm(root,{recursive:true,force:true})};}
async function rejectContent(name,content,pattern){test(name,async()=>{const fx=await fixture(content);try{await assert.rejects(()=>fx.provider(),pattern);}finally{await fx.cleanup();}});}

test("valid RSA3072 SPKI is accepted with deterministic separately-bound fingerprint",async()=>{const fx=await fixture();try{const one=await fx.provider(),two=await fx.provider(),fingerprint=operatorPublicKeyFingerprint(one);assert.equal(operatorPublicKeyFingerprint(two),fingerprint);const binding=await loadTestTrustedOperatorBinding({publicKeyProvider:fx.provider,approvedFingerprintProvider:async()=>fingerprint});assert.equal(binding.approvedOperatorKeyFingerprint,fingerprint);}finally{await fx.cleanup();}});
await rejectContent("RSA2048 is rejected",key("rsa",2048),/TRUSTED_RSA_KEY_TOO_WEAK/);
await rejectContent("EC is rejected",key("ec"),/TRUSTED_KEY_MUST_BE_RSA/);
test("private key PEM is rejected",async()=>{const pair=generateKeyPairSync("rsa",{modulusLength:3072}),fx=await fixture(pair.privateKey.export({type:"pkcs8",format:"pem"}));try{await assert.rejects(()=>fx.provider(),/PUBLIC_KEY_CONTAINER_REJECTED/);}finally{await fx.cleanup();}});
await rejectContent("malformed PEM is rejected","-----BEGIN PUBLIC KEY-----\nbad\n-----END PUBLIC KEY-----\n",/MALFORMED/);
await rejectContent("multiple PEM objects are rejected",`${key()}${key()}`,/PUBLIC_KEY_CONTAINER_REJECTED/);
await rejectContent("empty file is rejected",Buffer.alloc(0),/PUBLIC_KEY_EMPTY/);
await rejectContent("oversize file is rejected",Buffer.alloc(MAX_PUBLIC_KEY_BYTES+1,0x41),/PUBLIC_KEY_TOO_LARGE/);
await rejectContent("BOM input is rejected",Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),Buffer.from(key())]),/PUBLIC_KEY_BOM_REJECTED/);
test("fingerprint missing, uppercase, malformed, and mismatch fail closed",async()=>{const fx=await fixture();try{const fingerprint=operatorPublicKeyFingerprint(await fx.provider());for(const value of [undefined,fingerprint.toUpperCase(),"sha256:xyz",`sha256:${"0".repeat(64)}`])await assert.rejects(()=>loadTestTrustedOperatorBinding({publicKeyProvider:fx.provider,approvedFingerprintProvider:async()=>value}),/FINGERPRINT/);}finally{await fx.cleanup();}});
test("alternate and traversal paths are rejected",async()=>{const fx=await fixture();try{await assert.rejects(()=>fx.provider(path.join(fx.root,"other.pem")),/ALTERNATE_PATH/);await assert.rejects(()=>fx.provider(`${fx.root}\\..\\${path.basename(fx.root)}\\operator-public.pem`),/TRAVERSAL/);}finally{await fx.cleanup();}});
test("relative and UNC paths are rejected and legacy reopen Production construction is closed",async()=>{const fx=await fixture();try{await assert.rejects(()=>fx.provider("operator-public.pem"),/NOT_ABSOLUTE/);await assert.rejects(()=>fx.provider("\\\\server\\share\\operator-public.pem"),/UNC/);assert.throws(()=>createProductionTrustedOperatorPublicKeyProvider(),/LEGACY_REOPEN_PROVIDER_PRODUCTION_REJECTED/);}finally{await fx.cleanup();}});
test("reparse/symlink inspector result is rejected",async()=>{const fx=await fixture();try{const overrides={[path.win32.normalize(fx.file).toLowerCase()]:acl({reparse:true})},provider=createTestTrustedOperatorPublicKeyProvider({expectedPath:fx.file,approvedRoot:fx.root,aclInspector:inspector(fx.root,overrides),runnerPrincipal:RUNNER,provisionerPrincipals:[ADMIN]});await assert.rejects(()=>provider(),/REPARSE/);}finally{await fx.cleanup();}});
test("directory and missing file are rejected",async()=>{const root=await mkdtemp(path.join(tmpdir(),"runner-key-dir-"));try{const dir=path.join(root,"operator-public.pem");await mkdir(dir);let provider=createTestTrustedOperatorPublicKeyProvider({expectedPath:dir,approvedRoot:root,aclInspector:inspector(root)});await assert.rejects(()=>provider(),/NOT_REGULAR_FILE/);provider=createTestTrustedOperatorPublicKeyProvider({expectedPath:path.join(root,"missing.pem"),approvedRoot:root,aclInspector:inspector(root)});await assert.rejects(()=>provider());}finally{await rm(root,{recursive:true,force:true});}});
test("unacceptable or unavailable ACL, owner, inheritance, and handle identity are rejected",async()=>{const cases=[acl({available:false}),acl({owner:"UNAPPROVED"}),acl({inheritanceEnabled:true}),acl({entries:[{principal:RUNNER,permissions:["READ","WRITE","READ_ATTRIBUTES","READ_PERMISSIONS"]},{principal:SYSTEM,permissions:["FULL_CONTROL"]},{principal:ADMIN,permissions:["FULL_CONTROL"]}]})];for(const report of cases){const fx=await fixture();try{const provider=createTestTrustedOperatorPublicKeyProvider({expectedPath:fx.file,approvedRoot:fx.root,aclInspector:inspector(fx.root,{handle:report}),runnerPrincipal:RUNNER,provisionerPrincipals:[ADMIN]});await assert.rejects(()=>provider());}finally{await fx.cleanup();}}const fx=await fixture();try{const provider=createTestTrustedOperatorPublicKeyProvider({expectedPath:fx.file,approvedRoot:fx.root,aclInspector:inspector(fx.root,{handle:acl({fileId:"changed"})}),runnerPrincipal:RUNNER,provisionerPrincipals:[ADMIN]});await assert.rejects(()=>provider(),/IDENTITY/);}finally{await fx.cleanup();}});
test("ACL inspector absence fails closed",async()=>{assert.throws(()=>createTestTrustedOperatorPublicKeyProvider({expectedPath:"C:\\fixture\\operator-public.pem",aclInspector:null}),/ACL_INSPECTOR_REQUIRED/);});
test("key material is absent from stdout/stderr and DATABASE_URL is untouched",async()=>{const fx=await fixture(),before=process.env.DATABASE_URL,out=[],err=[],oldOut=process.stdout.write,oldErr=process.stderr.write;process.stdout.write=value=>(out.push(String(value)),true);process.stderr.write=value=>(err.push(String(value)),true);try{await fx.provider();}finally{process.stdout.write=oldOut;process.stderr.write=oldErr;await fx.cleanup();}assert.equal(process.env.DATABASE_URL,before);assert.equal(out.length,0);assert.equal(err.length,0);});
test("rejected private-key material is absent from stdout and stderr",async()=>{const pair=generateKeyPairSync("rsa",{modulusLength:3072}),privatePem=pair.privateKey.export({type:"pkcs8",format:"pem"}),fx=await fixture(privatePem),out=[],err=[],oldOut=process.stdout.write,oldErr=process.stderr.write;process.stdout.write=value=>(out.push(String(value)),true);process.stderr.write=value=>(err.push(String(value)),true);try{await assert.rejects(()=>fx.provider());}finally{process.stdout.write=oldOut;process.stderr.write=oldErr;await fx.cleanup();}assert.ok(!out.join("").includes("PRIVATE KEY")&&!err.join("").includes("PRIVATE KEY"));});
