import test,{before,after} from "node:test";
import assert from "node:assert/strict";
import {execFileSync,spawn} from "node:child_process";
import {createHash,generateKeyPairSync} from "node:crypto";
import {mkdtemp,mkdir,writeFile,readFile,rm,copyFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createNativeWindowsAclInspector} from "../scripts/runner-v2/native-windows-acl-inspector.mjs";
import {createTestTrustedWindowsKeyReadProvider,loadTrustedKeyReadBinding,resolveProductionKeyReaderPath} from "../scripts/runner-v2/trusted-windows-key-reader.mjs";
import {operatorPublicKeyFingerprint} from "../scripts/runner-v2/trusted-operator-key.mjs";

const windowsOnly=process.platform==="win32"?test:test.skip,csc="C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\csc.exe";
const elevatedOwnerOnly=process.platform==="win32"&&process.env.SIGNALX_ELEVATED_OWNER_ACCEPTANCE==="1"?test:test.skip;
let root,trust,keyPath,readerPath,inspectorPath,inspector,publicKey,runnerSid="S-1-5-32-545",provisionerSid,readerHash,bootstrapRoot,fixtureDiagnostics;
function ps(script){return execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-EncodedCommand",Buffer.from(script,"utf16le").toString("base64")],{windowsHide:true,timeout:15000,stdio:["ignore","pipe","pipe"]});}
function psElevated(script){const encoded=Buffer.from(script,"utf16le").toString("base64"),launcher=`$p=Start-Process -FilePath 'powershell.exe' -Verb RunAs -Wait -PassThru -ArgumentList @('-NoProfile','-NonInteractive','-EncodedCommand','${encoded}');exit $p.ExitCode`;return execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",launcher],{windowsHide:false,timeout:60000,stdio:["ignore","pipe","pipe"]});}
function aclScript(target,isDirectory,{inheritance=false,broadWrite=false,runnerWrite=false,executable=false}={}){const p=target.replaceAll("'","''");return `$p='${p}';$d=$${isDirectory?"true":"false"};$s=if($d){New-Object Security.AccessControl.DirectorySecurity}else{New-Object Security.AccessControl.FileSecurity};$s.SetAccessRuleProtection($${inheritance?"false":"true"},$false);$me=[Security.Principal.WindowsIdentity]::GetCurrent().User;$s.SetOwner($me);$i=if($d){[Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit}else{[Security.AccessControl.InheritanceFlags]::None};$n=[Security.AccessControl.PropagationFlags]::None;$a=[Security.AccessControl.AccessControlType]::Allow;$u=New-Object Security.Principal.SecurityIdentifier('S-1-5-32-545');$sys=New-Object Security.Principal.SecurityIdentifier('S-1-5-18');$r=${isDirectory||executable?'[Security.AccessControl.FileSystemRights]::ReadAndExecute':'[Security.AccessControl.FileSystemRights]::Read'} -bor [Security.AccessControl.FileSystemRights]::Synchronize;$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($u,$r,$i,$n,$a)));$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($sys,[Security.AccessControl.FileSystemRights]::FullControl,$i,$n,$a)));$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($me,[Security.AccessControl.FileSystemRights]::FullControl,$i,$n,$a)));${broadWrite?"$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule((New-Object Security.Principal.SecurityIdentifier('S-1-5-11')),[Security.AccessControl.FileSystemRights]::Write,$i,$n,$a)));":""}${runnerWrite?"$s.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($u,[Security.AccessControl.FileSystemRights]::Delete,$i,$n,$a)));":""}if($d){(New-Object IO.DirectoryInfo($p)).SetAccessControl($s)}else{(New-Object IO.FileInfo($p)).SetAccessControl($s)}`;}
async function setKeyAcl(options={}){ps(aclScript(trust,true,options));ps(aclScript(keyPath,false,options));}
async function setReaderAcl(options={}){ps(aclScript(readerPath,false,{...options,executable:true}));}
async function sha(file){return`sha256:${createHash("sha256").update(await readFile(file)).digest("hex")}`;}
function reader(overrides={}){return createTestTrustedWindowsKeyReadProvider({helperPath:readerPath,keyPath,trustRoot:trust,runnerSid,provisionerSid,expectedHelperHash:readerHash,helperInspector:inspector,...overrides});}
function rightsDecision(objectType,principal,rights){return new Promise((resolve,reject)=>{const result=spawn(readerPath,["acl-rights-fixture",objectType,principal,rights],{windowsHide:true});result.on("error",reject).on("close",resolve);});}
function nativeResult(args){return new Promise((resolve,reject)=>{const stdout=[],stderr=[],result=spawn(readerPath,args,{windowsHide:true,stdio:["ignore","pipe","pipe"]});result.stdout.on("data",chunk=>stdout.push(chunk));result.stderr.on("data",chunk=>stderr.push(chunk));result.on("error",reject).on("close",code=>resolve({code,stdout:Buffer.concat(stdout),stderr:Buffer.concat(stderr)}));});}
function normalizeFinalPath(value){const raw=String(value);const withoutPrefix=raw.startsWith("\\\\?\\UNC\\")?`\\\\${raw.slice(8)}`:raw.startsWith("\\\\?\\")?raw.slice(4):raw;return path.win32.normalize(withoutPrefix).replace(/[\\/]+$/u,"").toLowerCase();}
function controlledComponents(target){const absolute=path.win32.resolve(target),parsed=path.win32.parse(absolute),parts=absolute.slice(parsed.root.length).split(/[\\/]+/u).filter(Boolean);let current=parsed.root;return[parsed.root,...parts.map(part=>(current=path.win32.join(current,part)))];}
async function inspectCanonicalPath(nativeInspector,target){const supplied=path.win32.resolve(target),result=await nativeInspector.inspectPath(supplied),normalized=normalizeFinalPath(supplied),resolved=normalizeFinalPath(result.resolvedPath);return{path:supplied,normalized,resolvedPath:result.resolvedPath,resolved,canonicalEqual:normalized===resolved,isReparsePoint:result.isReparsePoint===true};}
function filesystemType(target){const drive=path.win32.parse(path.win32.resolve(target)).root.replaceAll("'","''");return ps(`$d=[IO.DriveInfo]::new('${drive}');if(!$d.IsReady){throw 'FILESYSTEM_IDENTITY_UNAVAILABLE'};$d.DriveFormat`).toString("utf8").trim();}
async function selectFixtureRoot(nativeInspector){const candidates=[process.env.GITHUB_WORKSPACE,process.cwd(),path.win32.parse(process.cwd()).root,os.tmpdir()].filter(Boolean),seen=new Set(),rejections=[];for(const candidate of candidates){if(!path.win32.isAbsolute(candidate))continue;const normalized=normalizeFinalPath(candidate);if(seen.has(normalized))continue;seen.add(normalized);let created;try{created=await mkdtemp(path.join(path.win32.resolve(candidate),"signalx-trusted-reader-fixture-"));const filesystem=filesystemType(created),components=[];for(const component of controlledComponents(created))components.push(await inspectCanonicalPath(nativeInspector,component));const rootReport=components.at(-1),accepted=filesystem.toUpperCase()==="NTFS"&&rootReport.canonicalEqual&&!rootReport.isReparsePoint&&components.every(item=>item.canonicalEqual&&!item.isReparsePoint);if(accepted)return{root:created,diagnostics:{candidateRoot:path.win32.resolve(candidate),normalizedRoot:rootReport.normalized,handleResolvedRoot:rootReport.resolvedPath,canonicalEqual:rootReport.canonicalEqual,rootIsReparsePoint:rootReport.isReparsePoint,filesystem,components}};rejections.push({candidateRoot:path.win32.resolve(candidate),filesystem,canonicalEqual:rootReport.canonicalEqual,rootIsReparsePoint:rootReport.isReparsePoint,components});}catch(error){rejections.push({candidateRoot:path.win32.resolve(candidate),error:error instanceof Error?error.message:String(error)});}if(created)await rm(created,{recursive:true,force:true,maxRetries:3,retryDelay:50});}throw new Error(`NO_CANONICAL_REPARSE_FREE_FIXTURE_ROOT ${JSON.stringify(rejections)}`);}
before(async()=>{if(process.platform!=="win32")return;bootstrapRoot=await mkdtemp(path.join(os.tmpdir(),"signalx-acl-inspector-bootstrap-"));const bootstrapInspectorPath=path.join(bootstrapRoot,"native-acl-inspector.exe");execFileSync(csc,["/nologo","/target:exe","/platform:x64",`/out:${bootstrapInspectorPath}`,path.resolve("scripts/runner-v2/native-windows-acl-inspector-helper.cs")],{windowsHide:true,timeout:30000});const bootstrapInspector=createNativeWindowsAclInspector({helperPath:bootstrapInspectorPath}),selection=await selectFixtureRoot(bootstrapInspector);root=selection.root;fixtureDiagnostics=selection.diagnostics;trust=path.join(root,"trust");await mkdir(trust);keyPath=path.join(trust,"operator-public.pem");readerPath=path.join(root,"native-windows-key-reader.exe");inspectorPath=path.join(root,"native-acl-inspector.exe");execFileSync(csc,["/nologo","/target:exe","/platform:x64",`/out:${readerPath}`,path.resolve("scripts/runner-v2/trusted-windows-key-reader-helper.cs")],{windowsHide:true,timeout:30000});execFileSync(csc,["/nologo","/target:exe","/platform:x64",`/out:${inspectorPath}`,path.resolve("scripts/runner-v2/native-windows-acl-inspector-helper.cs")],{windowsHide:true,timeout:30000});await new Promise(resolve=>setTimeout(resolve,1000));publicKey=generateKeyPairSync("rsa",{modulusLength:3072,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}}).publicKey;await writeFile(keyPath,publicKey,"ascii");await setKeyAcl();await setReaderAcl();inspector=createNativeWindowsAclInspector({helperPath:inspectorPath});const controlled=[];for(const target of [root,trust,keyPath,readerPath,inspectorPath]){const report=await inspectCanonicalPath(inspector,target);assert.equal(report.canonicalEqual,true,`fixture path is not canonical: ${target}`);assert.equal(report.isReparsePoint,false,`fixture path is a reparse point: ${target}`);controlled.push(report);}fixtureDiagnostics={...fixtureDiagnostics,fixtureDirectoryPath:root,normalizedFixturePath:normalizeFinalPath(root),resolvedFixturePath:controlled[0].resolvedPath,helperSuppliedPath:readerPath,helperResolvedPath:controlled[3].resolvedPath,helperIsReparsePoint:controlled[3].isReparsePoint,controlledPaths:controlled};console.log(`RUNNER_V2_FIXTURE_DIAGNOSTICS ${JSON.stringify(fixtureDiagnostics)}`);provisionerSid=(await inspector.inspectPath(readerPath)).owner;readerHash=await sha(readerPath);});
after(async()=>{for(const candidate of [root,bootstrapRoot])if(candidate&&path.basename(candidate).startsWith(candidate===root?"signalx-trusted-reader-fixture-":"signalx-acl-inspector-bootstrap-"))await rm(candidate,{recursive:true,force:true,maxRetries:3,retryDelay:50});});

windowsOnly("Production helper path uses OS CommonApplicationData and ignores ProgramData environment override",()=>{const original=process.env.ProgramData;try{process.env.ProgramData="C:\\attacker-controlled";const actual=resolveProductionKeyReaderPath(),known=ps("[Environment]::GetFolderPath([Environment+SpecialFolder]::CommonApplicationData)").toString("utf8").trim();assert.equal(actual,path.win32.join(known,"SignalX","runner-v2","bin","native-windows-key-reader.exe"));assert.equal(actual.includes("attacker-controlled"),false);}finally{if(original===undefined)delete process.env.ProgramData;else process.env.ProgramData=original;}});

for(const right of ["WriteData","AppendData","WriteExtendedAttributes","WriteAttributes","Delete","ChangePermissions","TakeOwnership","Modify","FullControl"])windowsOnly(`native key ACL decision rejects runner ${right} only`,async()=>assert.equal(await rightsDecision("key","runner",right),31));
windowsOnly("native key ACL decision accepts raw read-only rights without ExecuteFile",async()=>assert.equal(await rightsDecision("key","runner","ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize"),0));
windowsOnly("native key ACL decision rejects missing ReadData",async()=>assert.equal(await rightsDecision("key","runner","ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize"),31));
windowsOnly("native key ACL decision rejects missing ReadAttributes",async()=>assert.equal(await rightsDecision("key","runner","ReadData, ReadExtendedAttributes, ReadPermissions, Synchronize"),31));
windowsOnly("native key ACL decision rejects missing ReadPermissions",async()=>assert.equal(await rightsDecision("key","runner","ReadData, ReadExtendedAttributes, ReadAttributes, Synchronize"),31));
windowsOnly("native key ACL decision rejects missing Synchronize",async()=>assert.equal(await rightsDecision("key","runner","ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions"),31));
windowsOnly("native directory ACL decision accepts raw traversal and read rights",async()=>assert.equal(await rightsDecision("directory","runner","ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, ExecuteFile, Synchronize"),0));
windowsOnly("native directory ACL decision rejects missing Traverse",async()=>assert.equal(await rightsDecision("directory","runner","ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize"),31));
windowsOnly("native ACL decision rejects broad principal single WriteData",async()=>assert.equal(await rightsDecision("key","broad","WriteData"),31));
windowsOnly("native failure exit-code contract remains collision-free",async()=>{const generic=await nativeResult(["invalid-request"]),owner=await nativeResult(["read-fixture",keyPath,trust,runnerSid,"S-1-5-32-544"]),acl=await nativeResult(["acl-rights-fixture","key","runner","WriteData"]);for(const [result,code] of [[generic,2],[owner,21],[acl,31]]){assert.equal(result.code,code);assert.equal(result.stdout.length,0);assert.equal(result.stderr.length,0);}});

windowsOnly("nominal fixture root and controlled paths are canonical and reparse-free",()=>{assert.equal(fixtureDiagnostics.filesystem.toUpperCase(),"NTFS");assert.equal(fixtureDiagnostics.canonicalEqual,true);assert.equal(fixtureDiagnostics.rootIsReparsePoint,false);assert.equal(fixtureDiagnostics.helperIsReparsePoint,false);assert.equal(fixtureDiagnostics.normalizedFixturePath,normalizeFinalPath(fixtureDiagnostics.resolvedFixturePath));assert.equal(normalizeFinalPath(fixtureDiagnostics.helperSuppliedPath),normalizeFinalPath(fixtureDiagnostics.helperResolvedPath));assert.ok(fixtureDiagnostics.components.every(item=>item.canonicalEqual&&!item.isReparsePoint));assert.ok(fixtureDiagnostics.controlledPaths.every(item=>item.canonicalEqual&&!item.isReparsePoint));});
windowsOnly("trusted helper validates and reads key through one handle",async()=>{await setKeyAcl();await setReaderAcl();const result=await reader()();assert.equal(result.metadata.sameHandle,true);assert.equal(result.key.toString("ascii"),publicKey);result.key.fill(0);});
windowsOnly("helper rejects inheritance, broad write, and runner write",async()=>{for(const options of [{inheritance:true},{broadWrite:true},{runnerWrite:true}]){await setKeyAcl(options);await assert.rejects(reader()(),/KEY_READER_FAILED/);}});
windowsOnly("helper rejects oversized and malformed keys; Node rejects RSA2048",async()=>{await setKeyAcl();await writeFile(keyPath,Buffer.alloc(16*1024+1,65));await setKeyAcl();await assert.rejects(reader()(),/KEY_READER_FAILED/);await writeFile(keyPath,"not pem","ascii");await setKeyAcl();const malformed=await reader()();await assert.rejects(loadTrustedKeyReadBinding({keyReadProvider:async()=>malformed,approvedFingerprintProvider:async()=>"sha256:"+"0".repeat(64)}));const weak=generateKeyPairSync("rsa",{modulusLength:2048,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}}).publicKey;await writeFile(keyPath,weak,"ascii");await setKeyAcl();const weakResult=await reader()();await assert.rejects(loadTrustedKeyReadBinding({keyReadProvider:async()=>weakResult,approvedFingerprintProvider:async()=>"sha256:"+"0".repeat(64)}));});
windowsOnly("RSA3072 and exact separate fingerprint bind successfully",async()=>{await writeFile(keyPath,publicKey,"ascii");await setKeyAcl();const binding=await loadTrustedKeyReadBinding({keyReadProvider:reader(),approvedFingerprintProvider:async()=>operatorPublicKeyFingerprint(publicKey)});assert.equal(binding.approvedOperatorKeyFingerprint,operatorPublicKeyFingerprint(publicKey));});
windowsOnly("fingerprint mismatch rejects and key buffer is zeroized",async()=>{await setKeyAcl();const result=await reader()();await assert.rejects(loadTrustedKeyReadBinding({keyReadProvider:async()=>result,approvedFingerprintProvider:async()=>"sha256:"+"0".repeat(64)}));assert.ok(result.key.every(byte=>byte===0));});
windowsOnly("helper hash mismatch and unacceptable helper ACL reject before execution",async()=>{await setReaderAcl();await assert.rejects(reader({expectedHelperHash:"sha256:"+"0".repeat(64)})(),/HELPER_HASH_MISMATCH/);await setReaderAcl({runnerWrite:true});await assert.rejects(reader()(),/HELPER_ACL_REJECTED|HELPER_RUNNER_ACL_REJECTED/);});
windowsOnly("helper self-reparse inspector state is rejected",async()=>{await setReaderAcl();const actual=await inspector.inspectPath(readerPath),selfReparseInspector={inspectPath:target=>normalizeFinalPath(target)===normalizeFinalPath(readerPath)?Promise.resolve({...actual,isReparsePoint:true}):inspector.inspectPath(target)};await assert.rejects(reader({helperInspector:selfReparseInspector})(),/HELPER_ACL_REJECTED/);});
windowsOnly("helper reparse and missing helper fail closed",async()=>{await setReaderAcl();const junction=path.join(root,"bin-junction");const bin=path.join(root,"bin");await mkdir(bin);const copy=path.join(bin,"native-windows-key-reader.exe");await writeFile(copy,await readFile(readerPath));ps(aclScript(copy,false,{executable:true}));ps(`New-Item -ItemType Junction -Path '${junction}' -Target '${bin}'|Out-Null`);const linked=path.join(junction,"native-windows-key-reader.exe");await assert.rejects(reader({helperPath:linked,expectedHelperHash:await sha(copy)})(),/HELPER_(ACL|IDENTITY|REPARSE)_REJECTED/);await assert.rejects(reader({helperPath:path.join(root,"missing.exe")})());});
windowsOnly("key path through an immediate controlled-root junction is rejected",async()=>{await setReaderAcl();const target=path.join(root,"key-target"),junction=path.join(root,"key-junction");await mkdir(target);const copiedKey=path.join(target,"operator-public.pem");await writeFile(copiedKey,publicKey,"ascii");ps(aclScript(target,true));ps(aclScript(copiedKey,false));ps(`New-Item -ItemType Junction -Path '${junction}' -Target '${target}'|Out-Null`);await assert.rejects(reader({trustRoot:junction,keyPath:path.join(junction,"operator-public.pem")})(),/KEY_READER_FAILED/);});
windowsOnly("native reader assigns reserved exit 22 only to direct key-file self-reparse",async()=>{await setReaderAcl();const directTrust=path.join(root,"direct-key-reparse-trust"),target=path.join(directTrust,"ordinary-target.pem"),linkedKey=path.join(directTrust,"operator-public.pem");await mkdir(directTrust);await writeFile(target,publicKey,"ascii");ps(aclScript(directTrust,true));ps(aclScript(target,false));ps(`New-Item -ItemType SymbolicLink -Path '${linkedKey}' -Target '${target}'|Out-Null`);const trustReport=await inspectCanonicalPath(inspector,directTrust),targetReport=await inspectCanonicalPath(inspector,target),linkReport=await inspector.inspectPath(linkedKey);assert.equal(trustReport.isReparsePoint,false);assert.equal(targetReport.isReparsePoint,false);assert.equal(linkReport.isReparsePoint,true);console.log(`RUNNER_V2_DIRECT_KEY_REPARSE_DIAGNOSTICS ${JSON.stringify({trustPath:directTrust,trustIsReparsePoint:trustReport.isReparsePoint,targetPath:target,targetIsReparsePoint:targetReport.isReparsePoint,suppliedKeyPath:linkedKey,suppliedKeyIsReparsePoint:linkReport.isReparsePoint,expectedExitCode:22})}`);const result=await nativeResult(["read-fixture",linkedKey,directTrust,runnerSid,provisionerSid]);assert.equal(result.code,22);assert.equal(result.stdout.length,0);assert.equal(result.stderr.length,0);await assert.rejects(reader({trustRoot:directTrust,keyPath:linkedKey})(),error=>error instanceof Error&&error.message==="KEY_READER_FAILED");});
windowsOnly("helper path through a higher controlled ancestor junction is rejected",async()=>{await setReaderAcl();const target=path.join(root,"outer-target"),nested=path.join(target,"nested"),junction=path.join(root,"outer-junction");await mkdir(nested,{recursive:true});const copy=path.join(nested,"native-windows-key-reader.exe");await writeFile(copy,await readFile(readerPath));ps(aclScript(copy,false,{executable:true}));ps(`New-Item -ItemType Junction -Path '${junction}' -Target '${target}'|Out-Null`);const linked=path.join(junction,"nested","native-windows-key-reader.exe");await assert.rejects(reader({helperPath:linked,expectedHelperHash:await sha(copy)})(),/HELPER_(ACL|IDENTITY|REPARSE)_REJECTED/);});
windowsOnly("helper binary replacement between hash and launch fails closed",async()=>{await setReaderAcl();const backup=path.join(root,"reader-backup.exe");await copyFile(readerPath,backup);let replaced=false;const replacingSpawn=(file,args,options)=>{if(!replaced){execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",`Copy-Item -LiteralPath '${inspectorPath}' -Destination '${readerPath}' -Force`],{windowsHide:true});ps(aclScript(readerPath,false,{}));replaced=true;}return spawn(file,args,options);};try{await assert.rejects(reader({spawnImpl:replacingSpawn})(),/KEY_READER_(FAILED|UNAVAILABLE)|HELPER_REPLACED/);}finally{await copyFile(backup,readerPath);await setReaderAcl();}assert.equal(replaced,true);});
windowsOnly("malformed framed protocol and raw helper failure fail closed without key forwarding",async()=>{await setReaderAcl();const fake=()=>{const handlers={},stream={on(name,cb){handlers[name]=cb;return stream;}};queueMicrotask(()=>{handlers.data?.(Buffer.from("not-a-frame"));handlers.close?.(0);});return{stdout:stream,stderr:{on(){return this;}},on(name,cb){handlers[name]=cb;return this;},kill(){}};};await assert.rejects(reader({spawnImpl:fake})(),/PROTOCOL/);});
elevatedOwnerOnly("elevated actual unapproved owner SID is natively observed and rejected",async()=>{await writeFile(keyPath,publicKey,"ascii");await setKeyAcl();await setReaderAcl();const baseline=await reader()();baseline.key.fill(0);const before=await inspector.inspectPath(keyPath);assert.equal(before.owner,provisionerSid);const escaped=keyPath.replaceAll("'","''");psElevated(`$p='${escaped}';$s=(New-Object IO.FileInfo($p)).GetAccessControl([Security.AccessControl.AccessControlSections]::Owner -bor [Security.AccessControl.AccessControlSections]::Access);$s.SetOwner((New-Object Security.Principal.SecurityIdentifier('S-1-5-32-544')));(New-Object IO.FileInfo($p)).SetAccessControl($s)`);const changed=await inspector.inspectPath(keyPath);assert.equal(changed.owner,"S-1-5-32-544");try{await assert.rejects(reader()(),/KEY_READER_OWNER_REJECTED/);}finally{psElevated(`$p='${escaped}';$s=(New-Object IO.FileInfo($p)).GetAccessControl([Security.AccessControl.AccessControlSections]::Owner -bor [Security.AccessControl.AccessControlSections]::Access);$s.SetOwner((New-Object Security.Principal.SecurityIdentifier('${provisionerSid}')));(New-Object IO.FileInfo($p)).SetAccessControl($s)`);await setKeyAcl();}});
test.skip("approved SYSTEM owner requires a separately privileged fixture token",()=>{});
