"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type S={sample_count:number;completed_5d_count:number;avg_return_1d:number|null;avg_return_3d:number|null;avg_return_5d:number|null;median_return_5d:number|null;positive_rate_5d:number|null;distinct_codes:number;distinct_dates:number};
type C={trade_date:string;code:string;name:string;current_ai_power:number;previous_ai_power:number;prior_3record_return:number;market_pattern:string|null;result_1d:number|null;result_3d:number|null;result_5d:number|null};
type P={summary:S;candidates:C[]};
const pct=(v:number|null)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;
export default function Page(){const[data,setData]=useState<P|null>(null);const[error,setError]=useState("");
useEffect(()=>{fetch("/api/admin/high-ai-pullback",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||"取得失敗");setData(p)}).catch(e=>setError(e instanceof Error?e.message:"取得失敗"))},[]);
return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-950"><div className="mx-auto max-w-7xl">
<header className="rounded-3xl border bg-white p-5 shadow-sm"><Link href="/admin/learning-status" className="text-sm font-bold text-blue-600">← 学習監視</Link><p className="mt-4 text-xs font-black tracking-[.16em] text-violet-600">ADMIN RESEARCH / HAP_V1</p><h1 className="mt-2 text-3xl font-black">💎 高AI・押し目研究</h1><p className="mt-2 text-sm text-slate-500">AI POWER 90以上×2、MACD_GC×2、直近3記録日で下落した銘柄を未来データだけで追跡。買い推奨・一般通知には未接続です。</p><div className="mt-4 inline-flex rounded-full bg-amber-100 px-4 py-2 text-sm font-black text-amber-800">COLLECTING — 研究データ収集中</div></header>
{error&&<p className="mt-5 rounded-2xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}
{data&&<><section className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[["候補",data.summary.sample_count+"件"],["5日完了",data.summary.completed_5d_count+"件"],["5日平均",pct(data.summary.avg_return_5d)],["5日プラス率",data.summary.positive_rate_5d==null?"—":Number(data.summary.positive_rate_5d).toFixed(1)+"%"]].map(([a,b])=><div key={a} className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">{a}</p><p className="mt-1 text-2xl font-black">{b}</p></div>)}</section>
<section className="mt-5 overflow-hidden rounded-3xl border bg-white"><div className="p-5"><h2 className="text-xl font-black">FORWARD候補</h2><p className="mt-1 text-sm text-slate-500">1・3・5記録日後を自動追跡します。</p></div><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-100 text-left"><tr>{["日付","銘柄","AI","前回AI","直近3日","相場","1日","3日","5日","CHART"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{data.candidates.map(c=><tr key={c.trade_date+c.code} className="border-t"><td className="px-3 py-3">{String(c.trade_date).slice(0,10)}</td><td className="px-3 py-3 font-bold">{c.name} ({c.code})</td><td className="px-3 py-3">{Number(c.current_ai_power).toFixed(1)}</td><td className="px-3 py-3">{Number(c.previous_ai_power).toFixed(1)}</td><td className="px-3 py-3">{pct(c.prior_3record_return)}</td><td className="px-3 py-3">{c.market_pattern||"—"}</td><td className="px-3 py-3">{pct(c.result_1d)}</td><td className="px-3 py-3">{pct(c.result_3d)}</td><td className="px-3 py-3 font-bold">{pct(c.result_5d)}</td><td className="px-3 py-3"><Link href={`/chart/${c.code}`} className="font-bold text-blue-600">見る →</Link></td></tr>)}</tbody></table>{data.candidates.length===0&&<p className="p-8 text-center text-slate-500">まだFORWARD候補はありません。条件成立時に自動追加されます。</p>}</div></section></>}
</div></main>}
