"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
type Item={trade_date:string;code:string;name:string;researches:string[];overlap_count:number;ai_power:number|null;reference_price:number|null;discovery_price:number|null;market_pattern:string|null;result_1d:number|null;result_3d:number|null;result_5d:number|null;mm_details:Record<string,unknown>|null;hap_details:Record<string,unknown>|null;air_details:Record<string,unknown>|null;tpr_details:Record<string,unknown>|null};
const labels:Record<string,string>={MM_V1:"爆益前兆",HAP_V1:"高AI押し目",AIR_V1:"AI反転",TPR_V1:"トレンド押し目"};
const reasons:Record<string,string>={MM_V1:"直近3回のAI POWERが高水準だった後、現在のAI POWERが50以下へ低下。反発するかを検証中。",HAP_V1:"AI POWERが2回連続90以上、MACDが2回連続GC。直近3記録の株価が下落した押し目候補。",AIR_V1:"直近3記録の株価が5%超下落し、AI POWERが前回から15以上50未満上昇、MACDがGC。反転するか検証中。",TPR_V1:"直近3記録の株価が5%超下落。RSI45〜60・MACD GC・VWAPより下・EMA20より上という条件が一致。"};
const metric=(v:unknown,suffix="")=>v==null?"—":(typeof v==="number"?v.toFixed(1):String(v))+suffix;
const details=(x:Item,r:string)=>{const d=(r==="MM_V1"?x.mm_details:r==="HAP_V1"?x.hap_details:r==="AIR_V1"?x.air_details:x.tpr_details)||{};if(r==="MM_V1")return `前3回AI平均 ${metric(d.prev3_avg_ai_power)} / 最大 ${metric(d.prev3_max_ai_power)} / 高AI回数 ${metric(d.prev3_high_count)} / 現在AI ${metric(d.current_ai_power)} / MACD ${metric(d.confirmation_key)}`;if(r==="HAP_V1")return `前回AI ${metric(d.previous_ai_power)} → 現在 ${metric(d.current_ai_power)} / 3記録騰落 ${metric(d.prior_3record_return,"%")} / MACD ${metric(d.previous_macd_key)} → ${metric(d.current_macd_key)}`;if(r==="AIR_V1")return `前回AI ${metric(d.previous_ai_power)} → 現在 ${metric(d.current_ai_power)}（変化 +${metric(d.ai_power_change)}）/ 3記録騰落 ${metric(d.prior_3record_return,"%")} / ${metric(d.current_macd_key)}`;return `3記録騰落 ${metric(d.prior_3record_return,"%")} / ${metric(d.rsi_band)} / ${metric(d.macd_key)} / ${metric(d.vwap_key)} / ${metric(d.ema20_key)}`;};
const fmt=(v:number|null)=>v==null?"追跡中":(Number(v)>0?"+":"")+Number(v).toFixed(2)+"%";
export default function ExplosiveWatch(){
 const [priceAudit,setPriceAudit]=useState<{total:number;saved:number;missing_with_source:number;missing_source:number;latest_candidate_date:string|null}|null>(null);
 const [comparison,setComparison]=useState<Record<string,{events:number;completed1:number;avg1:number|null;positive1:number|null;completed5:number;avg5:number|null}>>({}),[performance,setPerformance]=useState<Record<string,{completed:number;avg5:number|null}>>({}),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[mode,setMode]=useState("all");
 useEffect(()=>{fetch("/api/admin/explosive-watch",{cache:"no-store"}).then(async r=>{if(r.status===403)throw Error("管理者専用ページです");if(!r.ok)throw Error("データ取得に失敗しました");const x=await r.json();setItems(x.items||[]);setPerformance(x.performance||{});setComparison(x.comparison||{});setPriceAudit(x.priceAudit||null)}).catch(e=>setError(String(e.message||e))).finally(()=>setLoading(false))},[]);
 const yen=(n:number)=>Math.round(n).toLocaleString("ja-JP")+"円";
 const estimate=(x:Item)=>{if(x.researches.length!==1)return "検証待ち";const s=performance[x.researches[0]];if(!s||s.completed<20||s.avg5==null||!x.discovery_price)return "検証待ち";return yen(Number(x.discovery_price)*100*Number(s.avg5)/100)+"（参考）";};
 const shown=useMemo(()=>items.filter(x=>mode==="all"||mode==="overlap"&&x.overlap_count>=2||x.researches.includes(mode)),[items,mode]);
 return <main className="min-h-screen bg-white px-2 py-3 text-slate-900"><div className="mx-auto max-w-5xl">
 <Link href="/admin/research-lab" className="text-xs font-bold text-blue-700">← 鉱脈研究所</Link>
 <div className="mt-2 flex flex-wrap items-baseline gap-x-3 gap-y-1"><h1 className="text-xl font-black">🚀 爆上げ候補ウォッチ</h1><span className="text-sm font-bold text-slate-500">{items.length}件 <span className="text-xs font-normal">（最大200件）</span></span></div>
 <p className="mt-1 text-[10px] text-slate-500">管理者専用・FORWARD研究候補／上昇保証や売買推奨ではありません</p>
 <details className="mt-3 rounded-xl border border-slate-300 bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-black">🧾 発見時価格の保存監査 {priceAudit?(`（${priceAudit.saved}/${priceAudit.total}件）`):""}</summary><div className="mt-2 grid grid-cols-2 gap-2 text-sm"><p>候補総数：<b>{priceAudit?.total??"—"}件</b></p><p>価格保存済み：<b>{priceAudit?.saved??"—"}件</b></p><p>元データあり・未保存：<b>{priceAudit?.missing_with_source??"—"}件</b></p><p>元データなし：<b>{priceAudit?.missing_source??"—"}件</b></p></div><p className="mt-2 text-xs text-slate-600">未保存の理由を区別して表示。記録は日次学習処理で実行し、この画面は確認専用です。</p></details>
 <div className="mt-3 flex flex-wrap gap-1.5">{[{id:"all",label:"すべて"},{id:"overlap",label:"🔥 複数一致"},...Object.entries(labels).map(([id,label])=>({id,label}))].map(x=><button key={x.id} onClick={()=>setMode(x.id)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${mode===x.id?"bg-blue-600 text-white":"border border-slate-300 bg-white text-slate-700"}`}>{x.label}</button>)}</div>
 {loading&&<p className="mt-5 text-sm">候補を読み込み中…</p>}{error&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {!loading&&!error&&shown.length===0&&<p className="mt-5 text-sm text-slate-500">該当する候補はまだありません。</p>}
 <details className="mt-3 rounded-xl border border-slate-300 bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-black">📊 研究一致数別の実績を比較（自動更新）</summary><div className="mt-3 grid grid-cols-2 gap-2">{[["multi","🔥 複数一致"],["single","1研究のみ"]].map(([key,label])=>{const s=comparison[key];return <div key={key} className="rounded-lg border bg-white p-3 text-sm"><p className="font-black">{label}</p><p className="mt-1">候補：{s?.events??0}件</p><p>翌日確定：{s?.completed1??0}件</p><p>翌日平均：{s?.completed1?fmt(s.avg1):"未確定"}</p><p>翌日プラス率：{s?.completed1?s.positive1+"%":"未確定"}</p><p>5日後確定：{s?.completed5??0}件</p><p>5日後平均：{s?.completed5?fmt(s.avg5):"未確定"}</p></div>})}</div><p className="mt-2 text-xs text-slate-600">件数が少ない間は優劣を判断できません。確定済みの未来データのみで比較しています。</p></details>
 <section className="mt-3 grid gap-2">{shown.map(x=><div key={x.trade_date+x.code} className="relative rounded-xl border border-slate-300 bg-white px-3 py-3 shadow-sm"><Link href={`/chart/${encodeURIComponent(x.code)}`} className="absolute bottom-2 right-3 z-10 rounded-lg bg-blue-50 px-3 py-1.5 text-sm font-bold text-blue-700">📈 CHART →</Link><details className="group pb-7">
 <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
 <div className="flex items-center gap-2">
 <span className="w-11 shrink-0 text-xs font-medium text-slate-500">{String(x.trade_date).slice(5,10).replace("-","/")}</span>
 <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-1.5 gap-y-1"><span className="text-base font-black">{x.name}</span><span className="text-xs text-slate-500">{x.code}</span>{x.researches.map(r=><span key={r} className="rounded bg-violet-50 px-2 py-0.5 text-xs font-bold text-violet-800">{labels[r]||r}</span>)}{x.overlap_count>=2&&<span className="rounded bg-orange-100 px-1 text-[10px] font-black text-orange-800">🔥{x.overlap_count}一致</span>}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-600"><span>AI <b className="text-slate-800">{x.ai_power==null?"—":Number(x.ai_power).toFixed(1)}</b></span><span>{x.market_pattern||"不明"}</span><span>1日 {fmt(x.result_1d)}</span><span>3日 {fmt(x.result_3d)}</span><span>5日 {fmt(x.result_5d)}</span></div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm"><span>100株（最新） <b className="text-slate-900">{x.reference_price?yen(Number(x.reference_price)*100):"価格未取得"}</b></span><span>期待利益目安 <b className="text-slate-900">{estimate(x)}</b></span></div></div>
 <span className="shrink-0 text-lg text-slate-600 group-open:rotate-180">⌄</span>
 </div></summary>
 <div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-4 text-base leading-7 text-amber-950"><p className="text-lg font-black">🔎 選出理由・判定時の数値</p><p className="mt-2 rounded-lg bg-white p-3 text-sm font-semibold">発見日の保存株価：{x.discovery_price?yen(Number(x.discovery_price))+"／株（100株 "+yen(Number(x.discovery_price)*100)+"）":"記録なし"}</p>{x.researches.map(r=><div key={r} className="mt-4"><b className="text-base">{labels[r]||r}：</b>{reasons[r]||"研究条件に一致したため追跡中。"}<p className="mt-2 rounded-lg border border-amber-100 bg-white p-3 text-base font-semibold leading-7 text-slate-900">{details(x,r)}</p></div>)}<p className="mt-3 text-sm leading-6 text-amber-800">発見時の条件であり、将来の上昇確率ではありません。</p></div>
 <div className="mt-3 flex flex-wrap items-center justify-between gap-3 text-sm"><span>1日 {fmt(x.result_1d)} ／ 3日 {fmt(x.result_3d)} ／ 5日 {fmt(x.result_5d)}</span><Link href={`/chart/${encodeURIComponent(x.code)}`} className="shrink-0 rounded-lg bg-blue-600 px-4 py-3 text-base font-bold text-white">CHART →</Link></div>
 </details></div>)}</section>
 </div></main>;
}
