"use client";

import { useEffect, useMemo, useState } from "react";

type Stock={code:string;name:string;price?:number;score?:number;aiPower?:number};
type Trade={id:number;code:string;name:string;entryPrice:number;investmentAmount:number;quantity:number;trackingDays:number|null;aiScore:number|null;aiLabel:string|null;status:"OPEN"|"CLOSED";startedAt:string;exitPrice:number|null};

export default function SimulationPage(){
 const [stocks,setStocks]=useState<Stock[]>([]),[trades,setTrades]=useState<Trade[]>([]),[q,setQ]=useState(""),[tab,setTab]=useState<"stocks"|"open"|"history">("stocks"),[buy,setBuy]=useState<Stock|null>(null),[amount,setAmount]=useState(50000),[days,setDays]=useState<number|null>(7),[busy,setBusy]=useState(false);
 async function load(){const [s,t]=await Promise.all([fetch("/api/scan?limit=200").then(r=>r.json()),fetch("/api/paper-trades").then(r=>r.json())]);setStocks(s.stocks||[]);setTrades(t.trades||[])}
 useEffect(()=>{load().catch(console.error)},[]);
 const shown=useMemo(()=>stocks.filter(s=>(s.code+" "+s.name).toLowerCase().includes(q.toLowerCase())).slice(0,100),[stocks,q]);
 async function submit(){if(!buy)return;setBusy(true);try{const r=await fetch("/api/paper-trades",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:buy.code,name:buy.name,entryPrice:Number(buy.price),investmentAmount:amount,trackingDays:days,aiScore:buy.score??buy.aiPower??null,aiLabel:(buy.score??buy.aiPower??0)>=75?"大本命":null})});const j=await r.json();if(!r.ok)throw new Error(j.error);setBuy(null);setTab("open");await load()}catch(e){alert(e instanceof Error?e.message:"失敗しました")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-md min-h-screen bg-white shadow-sm">
  <header className="sticky top-0 z-10 border-b bg-white/95 px-4 py-4 backdrop-blur"><h1 className="text-xl font-black">疑似投資</h1><p className="mt-1 text-xs text-slate-500">実際のお金を使わず、現実の株価で追跡します</p></header>
  <div className="grid grid-cols-3 border-b text-sm font-bold">{[["stocks","銘柄から選ぶ"],["open","保有中"],["history","履歴"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as typeof tab)} className={`py-3 ${tab===k?"border-b-2 border-blue-600 text-blue-600":"text-slate-500"}`}>{l}</button>)}</div>
  <div className="p-4">
  {tab==="stocks"&&<><input value={q} onChange={e=>setQ(e.target.value)} placeholder="銘柄名・コードで検索" className="mb-4 w-full rounded-xl bg-slate-100 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"/><div className="space-y-3">{shown.map(s=><div key={s.code} className="rounded-2xl border p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs text-slate-500">{s.code}</p><p className="font-bold">{s.name}</p><p className="mt-1 text-lg font-black">{Number(s.price||0).toLocaleString()}円</p></div><button disabled={!s.price} onClick={()=>setBuy(s)} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white disabled:bg-slate-300">疑似購入</button></div></div>)}</div></>}
  {tab==="open"&&<TradeList trades={trades.filter(t=>t.status==="OPEN")} stocks={stocks}/>} {tab==="history"&&<TradeList trades={trades.filter(t=>t.status==="CLOSED")} stocks={stocks}/>} 
  </div>
  {buy&&<div className="fixed inset-0 z-20 flex items-end justify-center bg-black/30"><div className="w-full max-w-md rounded-t-3xl bg-white p-5"><div className="flex justify-between"><div><p className="text-xs text-slate-500">{buy.code}</p><h2 className="text-xl font-black">{buy.name}</h2></div><button onClick={()=>setBuy(null)} className="text-2xl">×</button></div><p className="mt-3 text-3xl font-black">{Number(buy.price||0).toLocaleString()}円</p><p className="mt-5 text-sm font-bold">投資額</p><div className="mt-2 grid grid-cols-3 gap-2">{[10000,50000,100000].map(v=><button key={v} onClick={()=>setAmount(v)} className={`rounded-xl border py-3 text-sm font-bold ${amount===v?"border-blue-600 bg-blue-50 text-blue-600":""}`}>{v.toLocaleString()}円</button>)}</div><p className="mt-5 text-sm font-bold">追跡期間</p><div className="mt-2 grid grid-cols-4 gap-2">{[[3,"3日"],[7,"1週間"],[14,"2週間"],[null,"売るまで"]].map(([v,l])=><button key={String(v)} onClick={()=>setDays(v as number|null)} className={`rounded-xl border py-3 text-xs font-bold ${days===v?"border-blue-600 bg-blue-50 text-blue-600":""}`}>{l}</button>)}</div><button onClick={submit} disabled={busy} className="mt-6 w-full rounded-2xl bg-blue-600 py-4 font-black text-white">{busy?"開始中…":"この内容で疑似購入する"}</button></div></div>}
 </div></main>
}

function TradeList({trades,stocks}:{trades:Trade[];stocks:Stock[]}){if(!trades.length)return <div className="py-16 text-center text-sm text-slate-400">まだ取引はありません</div>;return <div className="space-y-3">{trades.map(t=>{const current=Number(stocks.find(s=>s.code===t.code)?.price||t.exitPrice||t.entryPrice);const pnl=(current-t.entryPrice)*t.quantity,pct=(current/t.entryPrice-1)*100;return <div key={t.id} className="rounded-2xl border p-4 shadow-sm"><div className="flex justify-between"><div><p className="text-xs text-slate-500">{t.code}</p><p className="font-bold">{t.name}</p></div><span className={`text-sm font-black ${pnl>=0?"text-emerald-600":"text-rose-600"}`}>{pnl>=0?"+":""}{Math.round(pnl).toLocaleString()}円 ({pct>=0?"+":""}{pct.toFixed(2)}%)</span></div><div className="mt-3 grid grid-cols-3 text-xs text-slate-500"><span>購入 {t.entryPrice.toLocaleString()}円</span><span>現在 {current.toLocaleString()}円</span><span>{t.trackingDays?`${t.trackingDays}日追跡`:"売るまで"}</span></div></div>})}</div>}
