import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import { authOptions } from "@/app/lib/auth";
import { cancelPaperTrade, closePaperTrade, createPaperTrade, getPaperTrades } from "@/app/lib/paperTrades";
export const dynamic="force-dynamic";
async function email(){const s=await getServerSession(authOptions);return s?.user?.email?.trim().toLowerCase()||null}
export async function GET(){const e=await email();if(!e)return NextResponse.json({success:false,error:"ログインが必要です"},{status:401});return NextResponse.json({success:true,trades:await getPaperTrades(e)})}
export async function POST(request:Request){try{const e=await email();if(!e)return NextResponse.json({success:false,error:"ログインが必要です"},{status:401});const b=await request.json();const entryPrice=Number(b.entryPrice),investmentAmount=Number(b.investmentAmount),trackingDays=b.trackingDays==null?null:Number(b.trackingDays);if(!b.code||!b.name||!Number.isFinite(entryPrice)||entryPrice<=0||!Number.isFinite(investmentAmount)||investmentAmount<=0)return NextResponse.json({success:false,error:"入力内容を確認してください"},{status:400});const trade=await createPaperTrade(e,{code:String(b.code),name:String(b.name),entryPrice,investmentAmount,trackingDays,aiScore:Number.isFinite(Number(b.aiScore))?Number(b.aiScore):null,aiLabel:b.aiLabel?String(b.aiLabel):null});return NextResponse.json({success:true,trade})}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:"疑似購入に失敗しました"},{status:500})}}
export async function PATCH(request:Request){const e=await email();if(!e)return NextResponse.json({success:false,error:"ログインが必要です"},{status:401});const b=await request.json(),id=Number(b.id),exitPrice=Number(b.exitPrice);if(!Number.isInteger(id)||!Number.isFinite(exitPrice)||exitPrice<=0)return NextResponse.json({success:false,error:"入力内容を確認してください"},{status:400});const trade=await closePaperTrade(e,id,exitPrice);return trade?NextResponse.json({success:true,trade}):NextResponse.json({success:false,error:"対象の取引がありません"},{status:404})}
export async function DELETE(request:Request){const e=await email();if(!e)return NextResponse.json({success:false,error:"ログインが必要です"},{status:401});const b=await request.json(),id=Number(b.id);if(!Number.isInteger(id))return NextResponse.json({success:false,error:"入力内容を確認してください"},{status:400});return await cancelPaperTrade(e,id)?NextResponse.json({success:true}):NextResponse.json({success:false,error:"対象の取引がありません"},{status:404})}
