import {NextResponse} from "next/server";
import YahooFinance from "yahoo-finance2";
export const dynamic="force-dynamic";
const yahooFinance=new YahooFinance({suppressNotices:["yahooSurvey"]});
const assets=[{symbol:"^GSPC",name:"S&P 500",icon:"🇺🇸"},{symbol:"^IXIC",name:"NASDAQ",icon:"💻"},{symbol:"^DJI",name:"NYダウ",icon:"🇺🇸"},{symbol:"USDJPY=X",name:"ドル/円",icon:"💱"},{symbol:"CL=F",name:"WTI原油",icon:"🛢️"},{symbol:"GC=F",name:"金",icon:"🥇"}];
function decodeXml(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim()}
function tag(item:string,name:string){const m=item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"));return m?decodeXml(m[1]):""}
async function googleNews(){try{const q=encodeURIComponent("日本株 OR 日経平均 OR 為替 OR 米国株 when:2d");const r=await fetch(`https://news.google.com/rss/search?q=${q}&hl=ja&gl=JP&ceid=JP:ja`,{headers:{"User-Agent":"Mozilla/5.0 SIGNALX/1.0"},cache:"no-store"});if(!r.ok)throw new Error(`rss ${r.status}`);const xml=await r.text();return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,8).map(m=>{const item=m[1],rawTitle=tag(item,"title"),link=tag(item,"link"),pubDate=tag(item,"pubDate");const parts=rawTitle.split(" - ");const publisher=parts.length>1?parts.pop()||"Google News":"Google News";return{title:parts.join(" - ")||rawTitle,link,publisher,providerPublishTime:pubDate}}).filter(n=>n.title&&n.link)}catch(e){console.error("weekend google news",e);return[]}}
export async function GET(){try{const quotes=await Promise.all(assets.map(async a=>{try{const q:any=await yahooFinance.quote(a.symbol);return{...a,price:q.regularMarketPrice??null,changePercent:q.regularMarketChangePercent??null,marketTime:q.regularMarketTime??null}}catch{return{...a,price:null,changePercent:null,marketTime:null}}}));let news:any[]=[];try{const queries=["Japan stocks","Nikkei 225","Japan economy"];for(const query of queries){const s:any=await yahooFinance.search(query,{newsCount:8,quotesCount:0});for(const n of s.news??[]){if(n?.title&&n?.link&&!news.some(x=>x.title===n.title))news.push({title:n.title,link:n.link,publisher:n.publisher,providerPublishTime:n.providerPublishTime??null})}if(news.length>=6)break}}catch(e){console.error("weekend yahoo news",e)}if(news.length<3){const rss=await googleNews();for(const n of rss){if(!news.some(x=>x.title===n.title))news.push(n)}}return NextResponse.json({success:true,quotes,news:news.slice(0,8),updatedAt:new Date().toISOString(),newsSource:news.length?"Yahoo Finance / Google News":"unavailable",note:"海外市場・為替等は取得できた直近値。休場中は直近取引日の終値です。ニュースは外部配信元の見出しです。"},{headers:{"Cache-Control":"public, s-maxage=300, stale-while-revalidate=600"}})}catch(e){console.error("weekend-context",e);return NextResponse.json({success:false,quotes:[],news:[],updatedAt:new Date().toISOString()},{status:200})}}
