import {NextResponse} from "next/server";
import YahooFinance from "yahoo-finance2";
export const dynamic="force-dynamic";
const yahooFinance=new YahooFinance({suppressNotices:["yahooSurvey"]});
const assets=[{symbol:"^GSPC",name:"S&P 500",icon:"🇺🇸"},{symbol:"^IXIC",name:"NASDAQ",icon:"💻"},{symbol:"^DJI",name:"NYダウ",icon:"🇺🇸"},{symbol:"USDJPY=X",name:"ドル/円",icon:"💱"},{symbol:"CL=F",name:"WTI原油",icon:"🛢️"},{symbol:"GC=F",name:"金",icon:"🥇"}];
type News={title:string;link:string;publisher?:string;providerPublishTime?:any;publishedAt?:string;source?:string;topic?:string};
function decodeXml(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim()}
function tag(item:string,name:string){const m=item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"));return m?decodeXml(m[1]):""}
function timeMs(v:any){if(!v)return 0;if(typeof v==="number")return v<1e12?v*1000:v;const n=Date.parse(v);return Number.isFinite(n)?n:0}
function topicOf(t:string){if(/円|為替|ドル|yen|currency/i.test(t))return"為替";if(/米国|NYダウ|NASDAQ|ナスダック|S&P|FRB|Fed|米株/i.test(t))return"米国市場";if(/日経|TOPIX|日本株|東証|株式/i.test(t))return"日本株";if(/原油|WTI|oil|金価格|gold/i.test(t))return"商品";if(/半導体|AI|chip/i.test(t))return"AI・半導体";return"市場"}
function cleanTitle(t:string){return t.replace(/\s+/g," ").trim()}
async function googleNews(query:string){try{const q=encodeURIComponent(`${query} when:3d`);const r=await fetch(`https://news.google.com/rss/search?q=${q}&hl=ja&gl=JP&ceid=JP:ja`,{headers:{"User-Agent":"Mozilla/5.0 SIGNALX/1.0"},cache:"no-store"});if(!r.ok)throw new Error(`rss ${r.status}`);const xml=await r.text();return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,12).map(m=>{const item=m[1],rawTitle=tag(item,"title"),link=tag(item,"link"),pubDate=tag(item,"pubDate");const parts=rawTitle.split(" - ");const publisher=parts.length>1?parts.pop()||"Google News":"Google News";const title=cleanTitle(parts.join(" - ")||rawTitle);return{title,link,publisher,providerPublishTime:pubDate,publishedAt:pubDate,source:"Google News",topic:topicOf(title)}}).filter(n=>n.title&&n.link)}catch(e){console.error("weekend google news",e);return[]}}
function pickFreshDiverse(items:News[]){const now=Date.now(),maxAge=72*60*60*1000;const seen=new Set<string>(),dedup=items.filter(n=>{const k=n.title.toLowerCase().replace(/[^\p{L}\p{N}]/gu,"").slice(0,45);if(!k||seen.has(k))return false;seen.add(k);return true}).map(n=>({...n,publishedAt:n.publishedAt||(timeMs(n.providerPublishTime)?new Date(timeMs(n.providerPublishTime)).toISOString():undefined),topic:n.topic||topicOf(n.title)}));const fresh=dedup.filter(n=>{const t=timeMs(n.providerPublishTime||n.publishedAt);return t>0&&now-t<=maxAge&&now-t>=-6*60*60*1000}).sort((a,b)=>timeMs(b.providerPublishTime||b.publishedAt)-timeMs(a.providerPublishTime||a.publishedAt));const pool=fresh.length?fresh:dedup.filter(n=>{const t=timeMs(n.providerPublishTime||n.publishedAt);return t>0&&now-t<=7*24*60*60*1000}).sort((a,b)=>timeMs(b.providerPublishTime||b.publishedAt)-timeMs(a.providerPublishTime||a.publishedAt));const out:News[]=[],topics=new Set<string>();for(const n of pool){if(!topics.has(n.topic||"市場")){out.push(n);topics.add(n.topic||"市場")}if(out.length===3)break}for(const n of pool){if(out.length===3)break;if(!out.includes(n))out.push(n)}return out}
export async function GET(){try{const quotes=await Promise.all(assets.map(async a=>{try{const q:any=await yahooFinance.quote(a.symbol);return{...a,price:q.regularMarketPrice??null,changePercent:q.regularMarketChangePercent??null,marketTime:q.regularMarketTime??null}}catch{return{...a,price:null,changePercent:null,marketTime:null}}}));let news:News[]=[];const rssQueries=["日本株 日経平均","ドル円 為替 日本市場","米国株 NASDAQ S&P500 日本株","半導体 AI 日本株"];const rssResults=await Promise.all(rssQueries.map(googleNews));news.push(...rssResults.flat());try{for(const query of ["Japan stocks","Nikkei 225","USD JPY"]){const s:any=await yahooFinance.search(query,{newsCount:8,quotesCount:0});for(const n of s.news??[]){if(n?.title&&n?.link)news.push({title:cleanTitle(n.title),link:n.link,publisher:n.publisher,providerPublishTime:n.providerPublishTime??null,source:"Yahoo Finance",topic:topicOf(n.title)})}}}catch(e){console.error("weekend yahoo news",e)}const selected=pickFreshDiverse(news);return NextResponse.json({success:true,quotes,news:selected,updatedAt:new Date().toISOString(),newsSource:selected.length?"Google News / Yahoo Finance":"unavailable",newsWindow:selected.length?"直近72時間を優先":"取得なし",note:"海外市場・為替等は取得できた直近値。休場中は直近取引日の終値です。ニュースは直近72時間の日本語市場ニュースを優先し、テーマが偏らないよう選定します。"},{headers:{"Cache-Control":"public, s-maxage=300, stale-while-revalidate=300"}})}catch(e){console.error("weekend-context",e);return NextResponse.json({success:false,quotes:[],news:[],updatedAt:new Date().toISOString()},{status:200})}}
