alter table public.momentum_memory_observations
 add column if not exists validation_mode text not null default 'BACKTEST',
 add column if not exists signal_version text not null default 'MM_V1';

update public.momentum_memory_observations
set validation_mode='BACKTEST', signal_version='MM_V1'
where validation_mode is distinct from 'BACKTEST' or signal_version is distinct from 'MM_V1';

create table if not exists public.momentum_memory_forward_stats (
 id bigint generated by default as identity primary key,
 profile_key text not null,
 confirmation_key text not null,
 signal_version text not null,
 sample_count int not null default 0,
 completed_5d_count int not null default 0,
 avg_return_5d numeric,
 median_return_5d numeric,
 positive_rate_5d numeric,
 updated_at timestamptz not null default now(),
 unique(profile_key,confirmation_key,signal_version)
);
alter table public.momentum_memory_forward_stats enable row level security;
revoke all on public.momentum_memory_forward_stats from anon,authenticated;
grant select,insert,update,delete on public.momentum_memory_forward_stats to service_role;
revoke all on sequence public.momentum_memory_forward_stats_id_seq from anon,authenticated;
grant usage,select on sequence public.momentum_memory_forward_stats_id_seq to service_role;