create table if not exists public.momentum_memory_observations (
  id bigint generated by default as identity primary key,
  trade_date date not null,
  code text not null,
  current_ai_power numeric,
  prev3_avg_ai_power numeric,
  prev3_max_ai_power numeric,
  prev3_high_count smallint not null default 0,
  last_settled_result_1 text,
  last_settled_result_2 text,
  ai_power_drop_from_peak numeric,
  observation_flag boolean not null default false,
  result_1d numeric,
  result_3d numeric,
  result_5d numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (trade_date, code)
);

create index if not exists momentum_memory_observations_code_date_idx
  on public.momentum_memory_observations (code, trade_date desc);

create index if not exists momentum_memory_observations_flag_date_idx
  on public.momentum_memory_observations (observation_flag, trade_date desc);

alter table public.momentum_memory_observations enable row level security;
revoke all on table public.momentum_memory_observations from anon, authenticated;
grant select, insert, update, delete on table public.momentum_memory_observations to service_role;
revoke all on sequence public.momentum_memory_observations_id_seq from anon, authenticated;
grant usage, select on sequence public.momentum_memory_observations_id_seq to service_role;
