create table if not exists public.momentum_memory_notifications (
 id bigint generated by default as identity primary key,
 observation_id bigint not null references public.momentum_memory_observations(id) on delete cascade,
 channel text not null default 'ADMIN_WEB_PUSH',
 sent_at timestamptz not null default now(),
 unique(observation_id,channel)
);
create index if not exists momentum_memory_notifications_sent_idx
 on public.momentum_memory_notifications(sent_at desc);
alter table public.momentum_memory_notifications enable row level security;
revoke all on public.momentum_memory_notifications from anon,authenticated;
grant select,insert,update,delete on public.momentum_memory_notifications to service_role;
revoke all on sequence public.momentum_memory_notifications_id_seq from anon,authenticated;
grant usage,select on sequence public.momentum_memory_notifications_id_seq to service_role;