create table if not exists public.pattern_forward_observations (
  id bigint generated by default as identity primary key,
  trade_date date not null,
  code text not null,
  pattern_id text not null,
  pattern_name text not null,
  direction text not null check (direction in ('BUY','SELL','NEUTRAL')),
  entry_price numeric not null check (entry_price > 0),
  confidence numeric,
  pattern_score numeric,
  return_1d numeric,
  return_3d numeric,
  return_5d numeric,
  success_1d boolean,
  success_3d boolean,
  success_5d boolean,
  outcome_1d_date date,
  outcome_3d_date date,
  outcome_5d_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (trade_date, code, pattern_id)
);

create index if not exists pattern_forward_observations_pattern_date_idx
  on public.pattern_forward_observations (pattern_id, trade_date desc);

create index if not exists pattern_forward_observations_code_date_idx
  on public.pattern_forward_observations (code, trade_date desc);

create table if not exists public.pattern_forward_stats (
  pattern_id text primary key,
  pattern_name text not null,
  direction text not null check (direction in ('BUY','SELL','NEUTRAL')),
  sample_count integer not null default 0,
  completed_1d_count integer not null default 0,
  completed_3d_count integer not null default 0,
  completed_5d_count integer not null default 0,
  win_rate_1d numeric,
  win_rate_3d numeric,
  win_rate_5d numeric,
  avg_directional_return_1d numeric,
  avg_directional_return_3d numeric,
  avg_directional_return_5d numeric,
  median_directional_return_5d numeric,
  avg_raw_return_1d numeric,
  avg_raw_return_3d numeric,
  avg_raw_return_5d numeric,
  distinct_codes integer not null default 0,
  distinct_dates integer not null default 0,
  validation_status text not null default 'COLLECTING'
    check (validation_status in ('COLLECTING','PROMISING','VALIDATED','OBSERVATION_ONLY')),
  status_reason text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.pattern_forward_observations enable row level security;
alter table public.pattern_forward_stats enable row level security;

revoke all on table public.pattern_forward_observations from anon, authenticated;
revoke all on table public.pattern_forward_stats from anon, authenticated;
grant select, insert, update, delete on table public.pattern_forward_observations to service_role;
grant select, insert, update, delete on table public.pattern_forward_stats to service_role;

revoke all on sequence public.pattern_forward_observations_id_seq from anon, authenticated;
grant usage, select on sequence public.pattern_forward_observations_id_seq to service_role;
